import type { CityData, FacilityNote, Place, PrayerName, Region, VerificationStatus } from './models.js';

const sampleFacility: FacilityNote = {
  womenPrayerSpace: 'Sample',
  wudu: 'Sample',
  accessibility: 'Sample',
  notes: 'Sample facility details; confirm locally before travel.',
};

const verifiedFacility: FacilityNote = {
  womenPrayerSpace: 'Verified',
  wudu: 'Verified',
  accessibility: 'Sample',
  notes: 'Verified in this mock dataset for prototype status-label testing only; reconfirm before travel.',
};

interface CitySpec {
  city: string;
  country: string;
  region: Region;
  timezone: string;
  coordinates: { lat: number; lng: number };
  prayerWindows: Record<PrayerName, string>;
  transportEstimates: CityData['transportEstimates'];
  attractions: Array<Pick<Place, 'name' | 'area' | 'description' | 'estimatedMinutes' | 'interests' | 'familyFriendly' | 'indoor'>>;
  mosque: Pick<Place, 'name' | 'area' | 'description' | 'estimatedMinutes'>;
  prayerSpace: Pick<Place, 'name' | 'area' | 'description' | 'estimatedMinutes'>;
  restaurant: Pick<Place, 'name' | 'area' | 'description' | 'estimatedMinutes' | 'budgetLevel'>;
  existingVerified?: boolean;
}

const windows = (fajr: string, dhuhr: string, asr: string, maghrib: string, isha: string): Record<PrayerName, string> => ({
  Fajr: fajr,
  Dhuhr: dhuhr,
  Asr: asr,
  Maghrib: maghrib,
  Isha: isha,
});

const transport = (walking: number, publicTransport: number, taxi: number, notes: string): CityData['transportEstimates'] => ({
  walking,
  publicTransport,
  taxi,
  notes,
});

const specs: CitySpec[] = [
  {
    city: 'Jerusalem',
    country: 'Palestine / Israel',
    region: 'Middle East',
    timezone: 'Asia/Jerusalem',
    coordinates: { lat: 31.778, lng: 35.235 },
    prayerWindows: windows('04:20-05:10', '12:35-13:45', '16:15-17:20', '19:45-20:20', '21:05-22:10'),
    transportEstimates: transport(24, 22, 16, 'Sample estimates; Old City gates and gradients can change walking time.'),
    attractions: [
      { name: 'Old City lanes', area: 'Old City', description: 'Sample heritage walk through layered markets, gates, and courtyards with frequent pauses.', estimatedMinutes: 90, interests: ['history', 'culture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Mount of Olives viewpoint', area: 'East Jerusalem', description: 'Sample scenic stop with a broad city panorama; plan extra time for slopes.', estimatedMinutes: 70, interests: ['history', 'views', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Al-Aqsa Mosque', area: 'Old City', description: 'Sample mosque/prayer option; access rules, opening times, and facilities are not live.', estimatedMinutes: 45 },
    prayerSpace: { name: 'Jerusalem quiet prayer room', area: 'Community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Levantine family kitchen', area: 'Near main route', description: 'Sample meal stop focused on familiar grilled plates and mezze-style options.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    timezone: 'Europe/London',
    coordinates: { lat: 51.507, lng: -0.128 },
    prayerWindows: windows('03:10-04:15', '13:05-14:15', '17:35-18:45', '21:10-21:45', '22:45-23:40'),
    transportEstimates: transport(20, 25, 18, 'Sample estimates using central London transit spacing.'),
    attractions: [
      { name: 'British Museum', area: 'Bloomsbury', description: 'Sample indoor culture stop with flexible galleries and rest-friendly pacing.', estimatedMinutes: 100, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: true },
      { name: 'Regent’s Park walk', area: 'Marylebone', description: 'Sample open-air break near the mosque, useful between museum time and prayer.', estimatedMinutes: 65, interests: ['walking', 'family', 'nature'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'London Central Mosque', area: 'Regent’s Park', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'London quiet prayer room', area: 'Museum or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Modest Turkish grill', area: 'Central route', description: 'Sample halal-conscious stop with grilled mains and vegetarian sides to ask about.', estimatedMinutes: 60, budgetLevel: 'mid' },
    existingVerified: true,
  },
  {
    city: 'Istanbul',
    country: 'Türkiye',
    region: 'Europe',
    timezone: 'Europe/Istanbul',
    coordinates: { lat: 41.008, lng: 28.978 },
    prayerWindows: windows('04:15-05:10', '13:05-14:05', '17:15-18:20', '20:35-21:05', '22:05-23:00'),
    transportEstimates: transport(18, 20, 14, 'Sample estimates; ferry or tram transfers may add time.'),
    attractions: [
      { name: 'Hagia Sophia area', area: 'Sultanahmet', description: 'Sample historic district stop with plazas, courtyards, and close-by rest options.', estimatedMinutes: 95, interests: ['history', 'architecture', 'culture'], familyFriendly: true, indoor: true },
      { name: 'Grand Bazaar lanes', area: 'Fatih', description: 'Sample covered-market visit for crafts and textiles; pacing can be adjusted easily.', estimatedMinutes: 80, interests: ['shopping', 'culture', 'walking'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Sultan Ahmed Mosque', area: 'Sultanahmet', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Istanbul quiet prayer room', area: 'Heritage district', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Ottoman lokanta', area: 'Sultanahmet route', description: 'Sample cafeteria-style meal stop with stews, rice, and vegetable dishes to confirm.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    timezone: 'Europe/Paris',
    coordinates: { lat: 48.857, lng: 2.352 },
    prayerWindows: windows('04:05-05:05', '13:45-14:45', '17:55-19:00', '21:35-22:05', '23:05-23:55'),
    transportEstimates: transport(22, 24, 17, 'Sample estimates for central metro and taxi hops.'),
    attractions: [
      { name: 'Louvre courtyard', area: '1st arrondissement', description: 'Sample art-and-architecture stop that can be enjoyed outside or extended indoors.', estimatedMinutes: 95, interests: ['culture', 'history', 'architecture'], familyFriendly: true, indoor: false },
      { name: 'Seine riverside walk', area: 'Central Paris', description: 'Sample gentle route with bridges, bookstalls, and easy breaks between sights.', estimatedMinutes: 70, interests: ['walking', 'views', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Grande Mosquée de Paris', area: '5th arrondissement', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Paris quiet prayer room', area: 'Museum or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'North African bistro', area: 'Left Bank route', description: 'Sample couscous-and-tagine style stop; ask staff about meat sourcing before ordering.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    timezone: 'Asia/Tokyo',
    coordinates: { lat: 35.676, lng: 139.65 },
    prayerWindows: windows('03:25-04:20', '11:45-12:45', '15:25-16:35', '18:55-19:25', '20:25-21:25'),
    transportEstimates: transport(16, 21, 18, 'Sample estimates; rail transfers are efficient but stations can be large.'),
    attractions: [
      { name: 'Asakusa district', area: 'Taito', description: 'Sample old-town visit with shopping streets, riverside space, and snack stops.', estimatedMinutes: 85, interests: ['culture', 'walking', 'family'], familyFriendly: true, indoor: false },
      { name: 'Ueno Park museums', area: 'Ueno', description: 'Sample flexible museum-and-park block with indoor alternatives for rain or heat.', estimatedMinutes: 100, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Tokyo Camii', area: 'Yoyogi-Uehara', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Tokyo quiet prayer room', area: 'Station or shopping-center area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Halal ramen house', area: 'Transit-friendly district', description: 'Sample halal-conscious noodle stop; verify current certificate or ingredient policy.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'New York',
    country: 'United States',
    region: 'North America',
    timezone: 'America/New_York',
    coordinates: { lat: 40.713, lng: -74.006 },
    prayerWindows: windows('04:00-05:00', '12:55-14:00', '17:05-18:15', '20:25-20:55', '21:55-22:50'),
    transportEstimates: transport(18, 24, 20, 'Sample estimates; traffic and subway service changes can be significant.'),
    attractions: [
      { name: 'Central Park', area: 'Manhattan', description: 'Sample green-space break with easy route shortening for families.', estimatedMinutes: 85, interests: ['family', 'walking', 'nature'], familyFriendly: true, indoor: false },
      { name: 'Metropolitan Museum steps', area: 'Upper East Side', description: 'Sample culture stop with an indoor museum option and outdoor neighborhood walk.', estimatedMinutes: 100, interests: ['culture', 'history', 'art'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Islamic Cultural Center of New York', area: 'Upper East Side', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'New York quiet prayer room', area: 'Museum or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Halal cart classics', area: 'Midtown route', description: 'Sample street-food style stop; ask about current preparation and cross-contact details.', estimatedMinutes: 45, budgetLevel: 'low' },
  },
  {
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    timezone: 'Asia/Dubai',
    coordinates: { lat: 25.204, lng: 55.271 },
    prayerWindows: windows('04:10-05:00', '12:20-13:20', '15:45-16:55', '19:05-19:35', '20:35-21:35'),
    transportEstimates: transport(14, 24, 16, 'Sample estimates; summer heat may make taxi or metro preferable.'),
    attractions: [
      { name: 'Dubai Creek abra ride', area: 'Deira / Bur Dubai', description: 'Sample waterfront crossing with heritage souks and short shaded segments.', estimatedMinutes: 80, interests: ['culture', 'walking', 'family'], familyFriendly: true, indoor: false },
      { name: 'Museum of the Future exterior', area: 'Trade Centre', description: 'Sample architecture stop that pairs well with metro access and indoor breaks nearby.', estimatedMinutes: 70, interests: ['architecture', 'family', 'culture'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Jumeirah Mosque', area: 'Jumeirah', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Dubai mall prayer room sample', area: 'Downtown', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Emirati grill sample kitchen', area: 'Deira route', description: 'Sample local meal stop; still confirm current halal handling and family seating.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
    timezone: 'Asia/Dubai',
    coordinates: { lat: 24.454, lng: 54.377 },
    prayerWindows: windows('04:15-05:05', '12:25-13:25', '15:50-17:00', '19:10-19:40', '20:40-21:40'),
    transportEstimates: transport(16, 28, 18, 'Sample estimates; attractions are spread out, so taxi times vary.'),
    attractions: [
      { name: 'Qasr Al Watan', area: 'Al Ras Al Akhdar', description: 'Sample palace-and-exhibits visit with strong indoor comfort for hot afternoons.', estimatedMinutes: 105, interests: ['history', 'culture', 'architecture'], familyFriendly: true, indoor: true },
      { name: 'Corniche waterfront', area: 'Corniche', description: 'Sample seaside walk with shaded pauses and easy taxi pickup points.', estimatedMinutes: 75, interests: ['walking', 'views', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Sheikh Zayed Grand Mosque', area: 'Al Rawdah', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 50 },
    prayerSpace: { name: 'Abu Dhabi quiet prayer room', area: 'Mall or cultural venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Gulf seafood sample cafe', area: 'Corniche route', description: 'Sample halal-conscious seafood stop; confirm kitchen practices before eating.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Doha',
    country: 'Qatar',
    region: 'Middle East',
    timezone: 'Asia/Qatar',
    coordinates: { lat: 25.285, lng: 51.531 },
    prayerWindows: windows('03:55-04:45', '11:40-12:40', '15:05-16:15', '18:25-18:55', '19:55-20:55'),
    transportEstimates: transport(15, 23, 15, 'Sample estimates; metro works well near central sights.'),
    attractions: [
      { name: 'Museum of Islamic Art park', area: 'Corniche', description: 'Sample culture-and-waterfront stop with indoor museum time as an option.', estimatedMinutes: 95, interests: ['culture', 'history', 'family'], familyFriendly: true, indoor: true },
      { name: 'Souq Waqif walk', area: 'Msheireb', description: 'Sample market route with spices, craft lanes, and evening-friendly pacing.', estimatedMinutes: 80, interests: ['shopping', 'culture', 'walking'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Imam Muhammad ibn Abd al-Wahhab Mosque', area: 'Jubailat', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Doha quiet prayer room', area: 'Cultural venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Qatari machboos sample kitchen', area: 'Souq route', description: 'Sample rice-and-grill meal stop; confirm current sourcing and preparation.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Riyadh',
    country: 'Saudi Arabia',
    region: 'Middle East',
    timezone: 'Asia/Riyadh',
    coordinates: { lat: 24.713, lng: 46.675 },
    prayerWindows: windows('03:50-04:40', '11:55-12:55', '15:20-16:30', '18:45-19:15', '20:15-21:15'),
    transportEstimates: transport(14, 28, 18, 'Sample estimates; car-based transfers are common between districts.'),
    attractions: [
      { name: 'Diriyah heritage district', area: 'Diriyah', description: 'Sample historic mudbrick quarter visit with evening-friendly outdoor pacing.', estimatedMinutes: 100, interests: ['history', 'culture', 'architecture'], familyFriendly: true, indoor: false },
      { name: 'National Museum sample visit', area: 'King Abdulaziz Historical Center', description: 'Sample indoor heritage stop with structured galleries and family pacing.', estimatedMinutes: 95, interests: ['history', 'family', 'culture'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'King Khalid Grand Mosque', area: 'Umm Al Hamam', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Riyadh quiet prayer room', area: 'Mall or museum area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Najdi sample dining room', area: 'Central route', description: 'Sample traditional meal stop; confirm current halal and family-area details.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Jeddah',
    country: 'Saudi Arabia',
    region: 'Middle East',
    timezone: 'Asia/Riyadh',
    coordinates: { lat: 21.543, lng: 39.173 },
    prayerWindows: windows('04:20-05:10', '12:25-13:25', '15:50-17:00', '19:15-19:45', '20:45-21:45'),
    transportEstimates: transport(16, 30, 20, 'Sample estimates; waterfront and old-town transfers can be traffic dependent.'),
    attractions: [
      { name: 'Al-Balad heritage lanes', area: 'Historic Jeddah', description: 'Sample old-town walk among coral-stone buildings, shops, and photo stops.', estimatedMinutes: 95, interests: ['history', 'culture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Jeddah Corniche', area: 'Red Sea waterfront', description: 'Sample relaxed waterfront route with play areas and sunset timing potential.', estimatedMinutes: 75, interests: ['views', 'family', 'walking'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'King Saud Mosque', area: 'Al-Sharafeyah', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Jeddah quiet prayer room', area: 'Waterfront or mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Hijazi seafood sample grill', area: 'Corniche route', description: 'Sample seafood-and-rice stop; ask about ingredients and kitchen handling.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Makkah',
    country: 'Saudi Arabia',
    region: 'Middle East',
    timezone: 'Asia/Riyadh',
    coordinates: { lat: 21.389, lng: 39.857 },
    prayerWindows: windows('04:15-05:05', '12:20-13:20', '15:45-16:55', '19:10-19:40', '20:40-21:40'),
    transportEstimates: transport(18, 24, 16, 'Sample estimates; crowd levels near the Haram can change routes quickly.'),
    attractions: [
      { name: 'Abraj Al Bait surroundings', area: 'Haram district', description: 'Sample central orientation stop with indoor breaks and crowded walkways.', estimatedMinutes: 70, interests: ['family', 'walking', 'views'], familyFriendly: true, indoor: true },
      { name: 'Makkah museum sample visit', area: 'Cultural district', description: 'Sample heritage stop for context around pilgrimage history and local craft.', estimatedMinutes: 85, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Masjid al-Haram', area: 'Haram district', description: 'Sample mosque/prayer option; crowd controls, access rules, and facilities are not live.', estimatedMinutes: 60 },
    prayerSpace: { name: 'Makkah quiet prayer area sample', area: 'Hotel or mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Makkah family mandi sample restaurant', area: 'Haram district route', description: 'Sample rice-and-grill meal stop; verify current preparation and queue times.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Madinah',
    country: 'Saudi Arabia',
    region: 'Middle East',
    timezone: 'Asia/Riyadh',
    coordinates: { lat: 24.524, lng: 39.569 },
    prayerWindows: windows('04:10-05:00', '12:25-13:25', '15:50-17:00', '19:15-19:45', '20:45-21:45'),
    transportEstimates: transport(18, 22, 15, 'Sample estimates; pedestrian zones near the mosque may affect drop-offs.'),
    attractions: [
      { name: 'Quba area visit', area: 'Quba', description: 'Sample short heritage stop with prayer-aware pacing and local shops nearby.', estimatedMinutes: 75, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: false },
      { name: 'Madinah museum sample visit', area: 'Central Madinah', description: 'Sample indoor learning stop that can fit between prayer windows.', estimatedMinutes: 85, interests: ['history', 'family', 'culture'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Al-Masjid an-Nabawi', area: 'Central Madinah', description: 'Sample mosque/prayer option; crowd controls, access rules, and facilities are not live.', estimatedMinutes: 60 },
    prayerSpace: { name: 'Madinah quiet prayer area sample', area: 'Hotel or mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Madinah date-market sample cafe', area: 'Central route', description: 'Sample light meal stop near market streets; confirm current ingredients.', estimatedMinutes: 50, budgetLevel: 'low' },
  },
  {
    city: 'Cairo',
    country: 'Egypt',
    region: 'Africa',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 30.044, lng: 31.236 },
    prayerWindows: windows('04:05-04:55', '12:55-13:55', '16:30-17:40', '20:00-20:30', '21:30-22:30'),
    transportEstimates: transport(20, 30, 22, 'Sample estimates; traffic can expand taxi times substantially.'),
    attractions: [
      { name: 'Khan el-Khalili lanes', area: 'Islamic Cairo', description: 'Sample market-and-craft walk with historic streets and flexible shopping pauses.', estimatedMinutes: 90, interests: ['culture', 'shopping', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Egyptian Museum sample visit', area: 'Tahrir', description: 'Sample indoor antiquities stop with a compact route for families.', estimatedMinutes: 105, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Al-Azhar Mosque', area: 'Islamic Cairo', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Cairo quiet prayer room', area: 'Museum or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Egyptian koshary sample stop', area: 'Downtown route', description: 'Sample vegetarian-friendly meal stop; ask about sauces and preparation.', estimatedMinutes: 45, budgetLevel: 'low' },
  },
  {
    city: 'Amman',
    country: 'Jordan',
    region: 'Middle East',
    timezone: 'Asia/Amman',
    coordinates: { lat: 31.953, lng: 35.91 },
    prayerWindows: windows('04:10-05:00', '12:40-13:40', '16:20-17:30', '19:55-20:25', '21:25-22:25'),
    transportEstimates: transport(22, 28, 18, 'Sample estimates; hills make short walks feel longer.'),
    attractions: [
      { name: 'Amman Citadel', area: 'Jabal Al Qala’a', description: 'Sample hilltop archaeology stop with city views and uneven paths.', estimatedMinutes: 85, interests: ['history', 'views', 'culture'], familyFriendly: true, indoor: false },
      { name: 'Rainbow Street stroll', area: 'Jabal Amman', description: 'Sample cafe-and-gallery walk with manageable segments and rest stops.', estimatedMinutes: 70, interests: ['walking', 'culture', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'King Abdullah I Mosque', area: 'Al Abdali', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Amman quiet prayer room', area: 'Mall or cultural venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Jordanian mansaf sample kitchen', area: 'Jabal Amman route', description: 'Sample local meal stop; confirm meat source and preparation with staff.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    timezone: 'Africa/Casablanca',
    coordinates: { lat: 31.629, lng: -7.981 },
    prayerWindows: windows('04:25-05:15', '13:35-14:35', '17:20-18:30', '20:45-21:15', '22:15-23:15'),
    transportEstimates: transport(18, 26, 16, 'Sample estimates; medina walking can be slow in crowded lanes.'),
    attractions: [
      { name: 'Jemaa el-Fnaa edges', area: 'Medina', description: 'Sample square-and-market route with early-evening energy and easy exits.', estimatedMinutes: 80, interests: ['culture', 'walking', 'family'], familyFriendly: true, indoor: false },
      { name: 'Bahia Palace', area: 'Medina', description: 'Sample architectural visit with courtyards, tilework, and shaded pauses.', estimatedMinutes: 90, interests: ['architecture', 'history', 'culture'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Koutoubia Mosque area', area: 'Medina', description: 'Sample mosque/prayer area option; access and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Marrakech riad prayer room sample', area: 'Medina accommodation area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Moroccan tagine sample terrace', area: 'Medina route', description: 'Sample tagine-style meal stop; verify current meat sourcing and preparation.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'Asia',
    timezone: 'Asia/Kuala_Lumpur',
    coordinates: { lat: 3.139, lng: 101.687 },
    prayerWindows: windows('05:40-06:30', '13:15-14:15', '16:40-17:50', '19:25-19:55', '20:55-21:55'),
    transportEstimates: transport(16, 22, 15, 'Sample estimates; rail is useful but heat favors short walks.'),
    attractions: [
      { name: 'Islamic Arts Museum Malaysia', area: 'Perdana Botanical Gardens', description: 'Sample indoor culture stop with calligraphy, textiles, and family-friendly galleries.', estimatedMinutes: 100, interests: ['culture', 'history', 'art'], familyFriendly: true, indoor: true },
      { name: 'KLCC Park', area: 'City Centre', description: 'Sample skyline walk with fountains, shade pockets, and mall access nearby.', estimatedMinutes: 75, interests: ['family', 'views', 'walking'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Masjid Negara', area: 'Kuala Lumpur city centre', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Kuala Lumpur mall surau sample', area: 'City Centre', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Malaysian nasi kandar sample counter', area: 'Transit-friendly district', description: 'Sample rice-and-curry meal stop; confirm current certification or supplier details.', estimatedMinutes: 50, budgetLevel: 'low' },
  },
  {
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    timezone: 'Asia/Singapore',
    coordinates: { lat: 1.352, lng: 103.82 },
    prayerWindows: windows('05:35-06:25', '13:05-14:05', '16:30-17:40', '19:15-19:45', '20:45-21:45'),
    transportEstimates: transport(15, 20, 14, 'Sample estimates; MRT transfers are predictable in central areas.'),
    attractions: [
      { name: 'Kampong Gelam walk', area: 'Bugis', description: 'Sample heritage district route with textiles, murals, and mosque proximity.', estimatedMinutes: 80, interests: ['culture', 'shopping', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Gardens by the Bay sample route', area: 'Marina Bay', description: 'Sample garden-and-conservatory visit with indoor cooling options.', estimatedMinutes: 105, interests: ['family', 'nature', 'views'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Sultan Mosque', area: 'Kampong Gelam', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Singapore mall prayer room sample', area: 'Marina or Orchard area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Malay hawker sample stall', area: 'Kampong Gelam route', description: 'Sample halal-conscious hawker stop; verify stall status and ingredients before ordering.', estimatedMinutes: 45, budgetLevel: 'low' },
  },
  {
    city: 'Jakarta',
    country: 'Indonesia',
    region: 'Asia',
    timezone: 'Asia/Jakarta',
    coordinates: { lat: -6.208, lng: 106.846 },
    prayerWindows: windows('04:35-05:25', '12:00-13:00', '15:20-16:30', '18:05-18:35', '19:35-20:35'),
    transportEstimates: transport(18, 30, 24, 'Sample estimates; traffic can dominate cross-city plans.'),
    attractions: [
      { name: 'Kota Tua square', area: 'Old Town', description: 'Sample colonial-era square visit with museums, cafes, and short walking loops.', estimatedMinutes: 90, interests: ['history', 'culture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'National Monument park', area: 'Central Jakarta', description: 'Sample landmark-and-park stop with open space and nearby transit.', estimatedMinutes: 80, interests: ['history', 'family', 'views'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Istiqlal Mosque', area: 'Central Jakarta', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 45 },
    prayerSpace: { name: 'Jakarta mall musholla sample', area: 'Central mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Indonesian padang sample house', area: 'Central route', description: 'Sample rice-and-dishes meal stop; confirm current halal status and ingredients.', estimatedMinutes: 50, budgetLevel: 'low' },
  },
  {
    city: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    timezone: 'Asia/Bangkok',
    coordinates: { lat: 13.756, lng: 100.501 },
    prayerWindows: windows('04:40-05:30', '12:20-13:20', '15:45-16:55', '18:45-19:15', '20:15-21:15'),
    transportEstimates: transport(18, 25, 20, 'Sample estimates; river, BTS, and taxi choices depend on district.'),
    attractions: [
      { name: 'Chao Phraya riverside', area: 'Old Bangkok', description: 'Sample boat-and-walk segment with temples, markets, and shaded pauses.', estimatedMinutes: 85, interests: ['views', 'culture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Jim Thompson House sample visit', area: 'Siam', description: 'Sample museum stop with indoor exhibits and garden spaces.', estimatedMinutes: 80, interests: ['culture', 'history', 'art'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Haroon Mosque', area: 'Bang Rak', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Bangkok mall prayer room sample', area: 'Siam or riverside area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Thai-Muslim sample curry shop', area: 'Bang Rak route', description: 'Sample curry-and-rice meal stop; ask about halal certification and ingredients.', estimatedMinutes: 50, budgetLevel: 'low' },
  },
  {
    city: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    timezone: 'Asia/Seoul',
    coordinates: { lat: 37.566, lng: 126.978 },
    prayerWindows: windows('03:30-04:25', '12:35-13:35', '16:10-17:20', '19:55-20:25', '21:25-22:25'),
    transportEstimates: transport(17, 22, 16, 'Sample estimates; subway exits and hills can affect final walking time.'),
    attractions: [
      { name: 'Bukchon Hanok Village', area: 'Jongno', description: 'Sample traditional-lane walk with steep sections and photo-friendly corners.', estimatedMinutes: 80, interests: ['culture', 'architecture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Namsan Seoul Tower area', area: 'Namsan', description: 'Sample viewpoint stop with cable-car or shuttle alternatives to reduce walking.', estimatedMinutes: 90, interests: ['views', 'family', 'walking'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Seoul Central Mosque', area: 'Itaewon', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Seoul quiet prayer room sample', area: 'Itaewon or shopping venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Korean bibimbap sample kitchen', area: 'Itaewon route', description: 'Sample halal-conscious Korean meal stop; verify meat sourcing and broths.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Toronto',
    country: 'Canada',
    region: 'North America',
    timezone: 'America/Toronto',
    coordinates: { lat: 43.653, lng: -79.383 },
    prayerWindows: windows('03:45-04:45', '13:20-14:20', '17:20-18:30', '21:05-21:35', '22:35-23:35'),
    transportEstimates: transport(19, 25, 18, 'Sample estimates; streetcar and subway transfers can shift by neighborhood.'),
    attractions: [
      { name: 'Royal Ontario Museum sample visit', area: 'Bloor-Yorkville', description: 'Sample indoor museum block with natural history and world culture exhibits.', estimatedMinutes: 105, interests: ['history', 'culture', 'family'], familyFriendly: true, indoor: true },
      { name: 'Harbourfront walk', area: 'Waterfront', description: 'Sample lakeside route with open views and simple rest stops.', estimatedMinutes: 75, interests: ['views', 'walking', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Masjid Toronto', area: 'Downtown', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Toronto quiet prayer room sample', area: 'University or mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Pakistani grill sample stop', area: 'Downtown route', description: 'Sample halal-conscious grill stop; ask for current certificate or supplier details.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Los Angeles',
    country: 'United States',
    region: 'North America',
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 34.052, lng: -118.244 },
    prayerWindows: windows('04:15-05:05', '12:55-13:55', '16:35-17:45', '20:05-20:35', '21:35-22:35'),
    transportEstimates: transport(22, 35, 28, 'Sample estimates; distances and traffic make transfers highly variable.'),
    attractions: [
      { name: 'Griffith Observatory grounds', area: 'Los Feliz', description: 'Sample viewpoint and science stop with sunset potential and walking grades.', estimatedMinutes: 95, interests: ['views', 'family', 'culture'], familyFriendly: true, indoor: true },
      { name: 'Getty Center sample visit', area: 'Brentwood', description: 'Sample art-and-garden visit with accessible tram flow and indoor galleries.', estimatedMinutes: 110, interests: ['art', 'architecture', 'family'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Islamic Center of Southern California', area: 'Koreatown', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Los Angeles quiet prayer room sample', area: 'Museum or campus area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'LA halal-conscious taco sample kitchen', area: 'Central route', description: 'Sample fusion meal stop; verify halal status, ingredients, and cross-contact.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Chicago',
    country: 'United States',
    region: 'North America',
    timezone: 'America/Chicago',
    coordinates: { lat: 41.878, lng: -87.63 },
    prayerWindows: windows('03:50-04:50', '12:55-13:55', '16:55-18:05', '20:30-21:00', '22:00-23:00'),
    transportEstimates: transport(18, 24, 18, 'Sample estimates; lakefront weather may affect walking comfort.'),
    attractions: [
      { name: 'Millennium Park', area: 'The Loop', description: 'Sample public-art and garden stop with easy looped walking routes.', estimatedMinutes: 75, interests: ['family', 'art', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Art Institute exterior and galleries', area: 'The Loop', description: 'Sample indoor culture block that can be shortened around prayer timing.', estimatedMinutes: 105, interests: ['art', 'culture', 'history'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Downtown Islamic Center', area: 'The Loop', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Chicago quiet prayer room sample', area: 'Museum or university area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Chicago halal-conscious bowl sample cafe', area: 'Loop route', description: 'Sample quick meal stop; ask about proteins, sauces, and current halal documentation.', estimatedMinutes: 50, budgetLevel: 'mid' },
  },
  {
    city: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    timezone: 'Europe/Madrid',
    coordinates: { lat: 41.387, lng: 2.168 },
    prayerWindows: windows('04:25-05:20', '13:55-14:55', '17:55-19:05', '21:20-21:50', '22:50-23:50'),
    transportEstimates: transport(19, 23, 17, 'Sample estimates; metro access is strong but old-town lanes slow walking.'),
    attractions: [
      { name: 'Gothic Quarter walk', area: 'Ciutat Vella', description: 'Sample medieval-lane route with plazas and shaded corners for short rests.', estimatedMinutes: 85, interests: ['history', 'architecture', 'walking'], familyFriendly: true, indoor: false },
      { name: 'Park Güell viewpoints', area: 'Gràcia', description: 'Sample mosaic-and-view stop; reserve extra time for hills and entry queues.', estimatedMinutes: 95, interests: ['architecture', 'views', 'family'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Centre Islàmic Camí de la Pau', area: 'Barcelona area', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Barcelona quiet prayer room sample', area: 'Shopping or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Mediterranean halal-conscious sample grill', area: 'Old city route', description: 'Sample kebab-and-salad stop; verify current halal sourcing with staff.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    timezone: 'Europe/Rome',
    coordinates: { lat: 41.903, lng: 12.496 },
    prayerWindows: windows('04:00-05:00', '13:15-14:15', '17:10-18:20', '20:45-21:15', '22:15-23:15'),
    transportEstimates: transport(20, 25, 18, 'Sample estimates; cobblestones and crowds can slow short walks.'),
    attractions: [
      { name: 'Colosseum exterior route', area: 'Ancient Rome', description: 'Sample archaeological walk with strong photo stops and optional ticketed entry.', estimatedMinutes: 95, interests: ['history', 'architecture', 'family'], familyFriendly: true, indoor: false },
      { name: 'Villa Borghese gardens', area: 'Pinciano', description: 'Sample park break with shade, viewpoints, and family-friendly pacing.', estimatedMinutes: 80, interests: ['walking', 'family', 'nature'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Mosque of Rome', area: 'Parioli', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Rome quiet prayer room sample', area: 'Station or community venue area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Rome halal-conscious pasta sample cafe', area: 'Central route', description: 'Sample Italian-style meal stop; ask about meat, cheese, and alcohol in sauces.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    timezone: 'Africa/Johannesburg',
    coordinates: { lat: -33.925, lng: 18.424 },
    prayerWindows: windows('05:45-06:35', '12:50-13:50', '15:35-16:45', '17:55-18:25', '19:25-20:25'),
    transportEstimates: transport(20, 30, 22, 'Sample estimates; use current local safety guidance before walking.'),
    attractions: [
      { name: 'Bo-Kaap streets', area: 'Bo-Kaap', description: 'Sample colorful heritage walk with Cape Malay history and short climbs.', estimatedMinutes: 75, interests: ['culture', 'history', 'walking'], familyFriendly: true, indoor: false },
      { name: 'V&A Waterfront', area: 'Waterfront', description: 'Sample harbor route with family activities, indoor shops, and easy transport access.', estimatedMinutes: 95, interests: ['family', 'views', 'shopping'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Auwal Mosque', area: 'Bo-Kaap', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Cape Town quiet prayer room sample', area: 'Waterfront or community area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Cape Malay sample kitchen', area: 'Bo-Kaap route', description: 'Sample curry-and-savoury meal stop; verify halal details and kitchen practices.', estimatedMinutes: 60, budgetLevel: 'mid' },
  },
  {
    city: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    timezone: 'Australia/Sydney',
    coordinates: { lat: -33.869, lng: 151.209 },
    prayerWindows: windows('05:20-06:10', '12:00-13:00', '14:45-15:55', '17:05-17:35', '18:35-19:35'),
    transportEstimates: transport(18, 25, 20, 'Sample estimates; ferries can be scenic but schedule-dependent.'),
    attractions: [
      { name: 'Circular Quay walk', area: 'Harbour', description: 'Sample harbor route with bridge views, ferry options, and frequent seating.', estimatedMinutes: 80, interests: ['views', 'walking', 'family'], familyFriendly: true, indoor: false },
      { name: 'Australian Museum sample visit', area: 'Darlinghurst', description: 'Sample indoor museum block with natural history and family-oriented exhibits.', estimatedMinutes: 95, interests: ['family', 'culture', 'history'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Sydney City Mosque', area: 'Surry Hills', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 35 },
    prayerSpace: { name: 'Sydney quiet prayer room sample', area: 'University or shopping area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Sydney halal-conscious laksa sample cafe', area: 'Central route', description: 'Sample noodle meal stop; ask about broth, meat sourcing, and preparation.', estimatedMinutes: 55, budgetLevel: 'mid' },
  },
  {
    city: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    region: 'Europe',
    timezone: 'Europe/Sarajevo',
    coordinates: { lat: 43.857, lng: 18.414 },
    prayerWindows: windows('03:35-04:35', '12:55-13:55', '17:00-18:10', '20:35-21:05', '22:05-23:05'),
    transportEstimates: transport(18, 22, 15, 'Sample estimates; old-town cobbles and hills can slow walking.'),
    attractions: [
      { name: 'Baščaršija bazaar', area: 'Old Town', description: 'Sample Ottoman-era market walk with crafts, cafes, and close prayer options.', estimatedMinutes: 85, interests: ['culture', 'history', 'shopping'], familyFriendly: true, indoor: false },
      { name: 'Latin Bridge area', area: 'Miljacka river', description: 'Sample compact history stop along the river with easy links back to the bazaar.', estimatedMinutes: 60, interests: ['history', 'walking', 'architecture'], familyFriendly: true, indoor: false },
    ],
    mosque: { name: 'Gazi Husrev-beg Mosque', area: 'Baščaršija', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Sarajevo quiet prayer room sample', area: 'Old Town or museum area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Bosnian ćevapi sample kitchen', area: 'Baščaršija route', description: 'Sample grilled meal stop; verify current halal status and preparation.', estimatedMinutes: 50, budgetLevel: 'low' },
  },
  {
    city: 'Tashkent',
    country: 'Uzbekistan',
    region: 'Asia',
    timezone: 'Asia/Tashkent',
    coordinates: { lat: 41.299, lng: 69.241 },
    prayerWindows: windows('03:35-04:25', '12:25-13:25', '16:25-17:35', '19:55-20:25', '21:25-22:25'),
    transportEstimates: transport(18, 23, 16, 'Sample estimates; metro is useful for central districts.'),
    attractions: [
      { name: 'Khast Imam complex', area: 'Old City', description: 'Sample religious-and-heritage complex visit with courtyards and museums nearby.', estimatedMinutes: 90, interests: ['history', 'culture', 'architecture'], familyFriendly: true, indoor: false },
      { name: 'Chorsu Bazaar', area: 'Old City', description: 'Sample market stop with produce domes, bread stalls, and lively local texture.', estimatedMinutes: 80, interests: ['shopping', 'culture', 'walking'], familyFriendly: true, indoor: true },
    ],
    mosque: { name: 'Minor Mosque', area: 'Anhor canal area', description: 'Sample mosque/prayer option; opening times and facilities are not live.', estimatedMinutes: 40 },
    prayerSpace: { name: 'Tashkent quiet prayer room sample', area: 'Bazaar or mall area', description: 'Sample fallback prayer space for itinerary planning only.', estimatedMinutes: 25 },
    restaurant: { name: 'Uzbek plov sample canteen', area: 'Old City route', description: 'Sample rice-and-meat meal stop; ask about ingredients and current halal handling.', estimatedMinutes: 55, budgetLevel: 'low' },
  },
];

const makePlaceId = (city: string, suffix: string) => `${city.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${suffix}`;

const restaurantHalalNote = 'Unverified sample listing only. Ask for current halal certificate, supplier details, or ingredient policy before eating.';

export const cities: CityData[] = specs.map((spec) => {
  const mosqueStatus: VerificationStatus = spec.existingVerified ? 'Verified' : 'Unverified';

  return {
    city: spec.city,
    country: spec.country,
    region: spec.region,
    timezone: spec.timezone,
    coordinates: spec.coordinates,
    prayerWindows: spec.prayerWindows,
    transportEstimates: spec.transportEstimates,
    places: [
      ...spec.attractions.map((attraction, index): Place => ({
        id: makePlaceId(spec.city, `a${index + 1}`),
        type: 'attraction',
        verification: spec.existingVerified && index === 0 ? 'Verified' : 'Sample',
        evidence: spec.existingVerified && index === 0 ? 'Mock verified entry included only so testers can see the Verified label state.' : undefined,
        ...attraction,
      })),
      {
        id: makePlaceId(spec.city, 'm1'),
        name: spec.mosque.name,
        type: 'mosque',
        area: spec.mosque.area,
        description: spec.mosque.description,
        estimatedMinutes: spec.mosque.estimatedMinutes,
        interests: ['prayer'],
        familyFriendly: true,
        indoor: true,
        verification: mosqueStatus,
        evidence: spec.existingVerified ? 'Mock verified facility record for prototype label testing; not live operational data.' : undefined,
        facility: spec.existingVerified ? verifiedFacility : sampleFacility,
      },
      {
        id: makePlaceId(spec.city, 'p1'),
        name: spec.prayerSpace.name,
        type: 'prayer-space',
        area: spec.prayerSpace.area,
        description: spec.prayerSpace.description,
        estimatedMinutes: spec.prayerSpace.estimatedMinutes,
        interests: ['prayer'],
        familyFriendly: true,
        indoor: true,
        verification: 'Sample',
        facility: sampleFacility,
      },
      {
        id: makePlaceId(spec.city, 'r1'),
        name: spec.restaurant.name,
        type: 'restaurant',
        area: spec.restaurant.area,
        description: spec.restaurant.description,
        estimatedMinutes: spec.restaurant.estimatedMinutes,
        interests: ['food'],
        familyFriendly: true,
        indoor: true,
        verification: 'Unverified',
        halalSupport: restaurantHalalNote,
        budgetLevel: spec.restaurant.budgetLevel,
      },
    ],
  };
});
