export const frenchExtraLabelsC: Record<string, string> = {
  toiletsTitle: "Toilettes publiques",
  toiletsSubtitle: "Trouvez des toilettes publiques cartographiées et des toilettes de lieux publics explicitement indiquées près de vous ou de votre destination.",
  toiletsOpen: "Toilettes publiques",
  toiletsBack: "Retour au planificateur",
  toiletsNotice: "Les informations sur les toilettes proviennent de données cartographiques contributives et peuvent être incomplètes ou obsolètes. Confirmez si possible l’accès, les horaires, les frais et l’accessibilité.",
  toiletsAccessNotice: "Accès inconnu ne signifie pas accès public. Les toilettes situées dans des commerces ou des lieux publics peuvent exiger un achat, un billet, une clé ou une autorisation.",
  toiletsUseLocation: "Utiliser ma position",
  toiletsManualSearch: "Rechercher une ville ou une destination",
  toiletsManualPlaceholder: "Ville, gare, parc...",
  toiletsSearch: "Rechercher",
  toiletsSearchThisArea: "Rechercher dans cette zone",
  toiletsRecentre: "Recentrer sur ma position",
  toiletsFitResults: "Afficher tous les résultats",
  toiletsRadius: "Rayon",
  toiletsRequestingLocation: "Demande de localisation...",
  toiletsSearching: "Recherche de toilettes cartographiées...",
  toiletsLocationDenied: "L’autorisation de localisation a été refusée. Recherchez plutôt une ville ou une destination.",
  toiletsLocationUnavailable: "La localisation n’est pas disponible sur cet appareil ou navigateur.",
  toiletsServiceUnavailable: "Service de données cartographiques indisponible. Réessayez dans un moment.",
  toiletsTimedOut: "La recherche a expiré. Essayez un rayon plus petit ou réessayez.",
  toiletsTooMany: "Trop de résultats. Essayez un rayon plus petit.",
  toiletsOffline: "Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.",
  toiletsCached: "Affichage des résultats de toilettes mis en cache.",
  toiletsNoResults: "Aucune toilette publique cartographiée n’a été trouvée dans cette zone. Cela ne signifie pas nécessairement qu’il n’en existe aucune.",
  toiletsNoPublic: "Aucune toilette publique confirmée ne correspond à ces filtres.",
  toiletsRetry: "Réessayer",
  toiletsIncreaseRadius: "Augmenter le rayon",
  toiletsSearchAnotherCity: "Rechercher une autre ville",
  toiletsMapView: "Carte",
  toiletsListView: "Liste à proximité",
  toiletsAllResults: "Tous les résultats",
  toiletsPublicAccess: "Accès public",
  toiletsCustomersOnly: "Clients ou visiteurs uniquement",
  toiletsRestricted: "Accès restreint",
  toiletsAccessUnknown: "Accès non confirmé",
  toiletsFree: "Gratuites",
  toiletsPaid: "Payantes",
  toiletsFeeUnknown: "Frais inconnus",
  toiletsOpenNow: "Ouvertes maintenant",
  toiletsOpen24: "Ouvertes 24 h/24",
  toiletsWheelchair: "Accessibles en fauteuil roulant",
  toiletsWheelchairLimited: "Accès limité en fauteuil roulant",
  toiletsWheelchairNo: "Non accessibles en fauteuil roulant",
  toiletsWheelchairUnknown: "Accessibilité inconnue",
  toiletsChanging: "Table à langer",
  toiletsFemale: "Femmes",
  toiletsMale: "Hommes",
  toiletsUnisex: "Unisexes",
  toiletsHandwashing: "Lavage des mains",
  toiletsSoap: "Savon",
  toiletsPaper: "Papier toilette",
  toiletsHotWater: "Eau chaude",
  toiletsShower: "Douche",
  toiletsDrinkingWater: "Eau potable",
  toiletsSeated: "Toilettes à siège",
  toiletsSquat: "Toilettes à la turque",
  toiletsUrinal: "Urinoir",
  toiletsOperator: "Exploitant",
  toiletsSupervised: "Surveillées",
  toiletsInside: "À l’intérieur",
  toiletsStandalone: "Toilettes publiques indépendantes",
  toiletsVenue: "Toilettes dans un lieu public",
  toiletsPortable: "Toilettes mobiles",
  toiletsSort: "Trier",
  toiletsNearest: "Les plus proches",
  toiletsSortName: "Nom",
  toiletsSortAccess: "Accès public en premier",
  toiletsSortFree: "Gratuites en premier",
  toiletsSortOpen: "Ouvertes maintenant",
  toiletsSortAccessible: "Accessibles en premier",
  toiletsLegend: "Légende des marqueurs",
};
