export const frenchTransportLabelsC: Record<string, string> = {
  taxiTitle: "Services de taxi",
  taxiSubtitle: "Trouvez les stations de taxi et les bureaux de taxi clairement identifiés près de votre position ou de votre destination.",
  taxiOpen: "Services de taxi",
  taxiBack: "Retour au planificateur",
  taxiNotice: "Les informations sur les taxis proviennent de données cartographiques contributives et peuvent être incomplètes ou obsolètes. Un point de taxi affiché ne prouve ni l’autorisation, ni la sécurité, ni le prix, ni la disponibilité actuelle. Confirmez localement les tarifs, les horaires, les moyens de paiement et les coordonnées officielles.",
  taxiLiveNotice: "Cette application ne permet pas encore de réserver un taxi ni d’afficher des véhicules en temps réel.",
  taxiUseLocation: "Utiliser ma position",
  taxiUseDestination: "Utiliser la destination du voyage",
  taxiManualSearch: "Rechercher une autre ville",
  taxiManualPlaceholder: "Ville ou destination...",
  taxiSearch: "Rechercher",
  taxiSearchThisArea: "Rechercher dans cette zone",
  taxiRecentre: "Recentrer la carte",
  taxiFitResults: "Afficher tous les résultats",
  taxiRadius: "Rayon",
  taxiRequestingLocation: "Demande de localisation...",
  taxiSearching: "Recherche de services de taxi cartographiés...",
  taxiLocationDenied: "L’autorisation de localisation a été refusée. Recherchez plutôt une destination.",
  taxiLocationUnavailable: "La localisation n’est pas disponible sur cet appareil ou navigateur.",
  taxiServiceUnavailable: "Service de données cartographiques indisponible. Réessayez dans un moment.",
  taxiTimedOut: "La recherche a expiré. Essayez un rayon plus petit ou réessayez.",
  taxiTooMany: "Trop de résultats. Essayez un rayon plus petit.",
  taxiOffline: "Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.",
  taxiCached: "Affichage des résultats de taxi mis en cache.",
  taxiNoResults: "Aucune station de taxi ni aucun bureau de taxi clairement identifié n’a été trouvé dans cette zone. Cela ne signifie pas nécessairement qu’il n’en existe aucun.",
  taxiRetry: "Réessayer",
  taxiIncreaseRadius: "Augmenter le rayon",
  taxiSearchAnother: "Rechercher une autre ville",
  taxiMapView: "Carte",
  taxiListView: "Liste à proximité",
  taxiAll: "Tous les services de taxi",
  taxiRank: "Station de taxi",
  taxiAirportRank: "Station de taxi d’aéroport",
  taxiStationRank: "Station de taxi de gare ferroviaire ou de métro",
  taxiBusRank: "Station de taxi de gare routière",
  taxiOffice: "Bureau de taxi ou service de répartition",
  taxiMotorcycle: "Station de moto-taxi",
  taxiWater: "Station de bateau-taxi",
  taxiOther: "Autre service de taxi cartographié",
  taxiPhoneAvailable: "Téléphone disponible",
  taxiWheelchairInfo: "Informations sur l’accessibilité en fauteuil roulant disponibles",
  taxiSort: "Trier",
  taxiSortType: "Type de service de taxi",
  taxiSortContact: "Coordonnées disponibles",
  taxiLegend: "Légende des marqueurs",
  taxiType: "Type de service de taxi",
  taxiCapacity: "Capacité",
  taxiVehicle: "Type de véhicule",
  taxiLit: "Éclairage",
  taxiFee: "Informations sur les tarifs",
  taxiCall: "Appeler le service de taxi",
};
