export const frenchFlightLabels: Record<string, string> = {
  flightModeTitle: "Prière et Qibla en vol",
  flightModeSubtitle: "Préparez un itinéraire de vol hors ligne pour les créneaux de prière et les estimations de la Qibla selon le cap réel en vol.",
  flightModeOpen: "Ouvrir le mode Vol",
  flightModeBack: "Retour au planificateur",
  flightPrepareStage: "Préparer le vol hors ligne",
  flightDashboardStage: "Tableau de bord en vol",
  flightBestEstimate: "Meilleure estimation disponible selon le GPS en direct ou l’itinéraire de vol enregistré.",
  flightOfflineNotice: "Les calculs de vol préparés sont disponibles hors ligne. La disponibilité du GPS en direct dépend de l’appareil, de l’avion, du siège et des restrictions de sécurité.",
  flightSafetyNotice: "Gardez votre appareil en mode Avion lorsque cela est exigé et suivez toutes les consignes de l’équipage.",
  flightRouteDisclaimer: "Un trajet direct d’aéroport à aéroport selon un grand cercle est une estimation et peut différer de l’itinéraire réel de la compagnie aérienne.",
  flightAltitudeDisclaimer: "À l’altitude de croisière, l’horizon visible et le lever ou le coucher du soleil observés peuvent différer des calculs au niveau du sol. Suivez les avis religieux auxquels vous faites confiance.",
  flightDepartureAirport: "Aéroport de départ",
  flightArrivalAirport: "Aéroport d’arrivée",
  flightAirportSearchHint: "Rechercher par code IATA, aéroport, ville ou pays",
  flightScheduledDepartureUtc: "Départ prévu (UTC)",
  flightDuration: "Durée prévue",
  flightHours: "heures",
  flightMinutes: "minutes",
  flightCruiseAltitude: "Altitude de croisière",
  flightAltitudeUnit: "Unité d’altitude",
  flightMeters: "mètres",
  flightFeet: "pieds",
  flightDepartureTimeZone: "Fuseau horaire de départ",
  flightArrivalTimeZone: "Fuseau horaire d’arrivée",
  flightWaypoints: "Points de passage facultatifs",
  flightWaypointHelp: "Un point par ligne : libellé, latitude, longitude",
  flightPrepareButton: "Préparer le vol hors ligne",
  flightUseTravelDetails: "Utiliser le vol enregistré dans Détails du voyage",
  flightEdit: "Modifier le vol",
  flightClear: "Effacer le vol",
  flightEnableGps: "Activer le GPS en direct",
  flightDisableGps: "Désactiver le GPS en direct",
  flightUseElapsed: "Utiliser l’estimation selon le temps écoulé",
  flightProgress: "Progression de l’itinéraire",
  flightProgressSlider: "Curseur de progression de l’itinéraire",
  flightSource: "Source",
  flightGpsSource: "GPS en direct",
  flightDerivedGpsSource: "Trajectoire GPS dérivée",
  flightRouteSource: "Estimation de l’itinéraire",
  flightUnavailableSource: "Indisponible",
  flightLastUpdate: "Dernière mise à jour",
  flightAccuracy: "Précision",
  flightLowAccuracy: "Précision GPS faible. L’estimation de l’itinéraire peut être plus stable.",
  flightGpsDenied: "L’autorisation de localisation a été refusée. Le mode Estimation de l’itinéraire reste disponible hors ligne.",
  flightGpsUnavailable: "Le GPS en direct est indisponible. Le mode Estimation de l’itinéraire reste disponible hors ligne.",
  flightGpsStale: "La mise à jour GPS est ancienne. Affichage de l’estimation de l’itinéraire.",
  flightCoordinates: "Coordonnées",
  flightAltitude: "Altitude",
  flightRemainingDistance: "Distance restante",
  flightRemainingTime: "Temps restant",
  flightRouteDistance: "Distance de l’itinéraire",
  flightQiblaTrue: "Direction de la Qibla",
  flightTrack: "Trajectoire GPS au sol",
  flightRelativeAngle: "Angle relatif de la Qibla",
  flightLeft: "à gauche",
  flightRight: "à droite",
  flightStraightAhead: "tout droit",
  flightBehind: "derrière",
  flightDiagramLabel: "Schéma de la trajectoire de l’avion et de la direction de la Qibla",
  flightConfidence: "Niveau de confiance",
  flightCurrentPrayer: "Créneau de prière actuel",
  flightNextPrayer: "Prochaine prière",
  flightPreviousPrayer: "Prière précédente",
  flightCountdown: "Compte à rebours",
  flightUtcPrayerTimes: "Heures de prière en UTC",
  flightZoneTimes: "Heures dans les fuseaux de départ et d’arrivée",
  flightMethod: "Méthode de calcul",
  flightNoPlan: "Préparez un vol avant d’utiliser le tableau de bord en vol.",
  flightPlanSaved: "Vol hors ligne enregistré.",
  flightPlanCleared: "Vol hors ligne effacé.",
  flightPlanInvalid: "Vérifiez les détails du vol et réessayez.",
  flightDifferentAirports: "Choisissez des aéroports de départ et d’arrivée différents.",
  flightInvalidDuration: "La durée doit être comprise entre 15 minutes et 24 heures.",
  flightInvalidWaypoint: "Un ou plusieurs points de passage n’ont pas pu être lus.",
  flightStorageRecovered: "Les données de vol enregistrées n’ont pas pu être lues et ont été ignorées.",
  flightAirportSource: "Données aéroportuaires : index hors ligne intégré dérivé des données du domaine public OurAirports.",
};
