export const frenchExtraLabelsA: Record<string, string> = {
  osmAttribution: "Données © contributeurs OpenStreetMap",
  attractionsSubtitle: "Trouvez des attractions touristiques cartographiées avec gestion des photos sous licence et de courts résumés provenant de sources en anglais.",
  attractionsNotice: "Les informations, photographies et résumés historiques proviennent de sources de données ouvertes et contributives et peuvent être incomplets ou obsolètes. Confirmez les horaires, l’accès, les prix d’entrée et les restrictions avant le voyage.",
  attractionsPhotoNotice: "Les photographies ne sont affichées que lorsqu’une correspondance fiable et une licence réutilisable sont disponibles.",
  attractionsLocationDenied: "L’autorisation de localisation a été refusée. Recherchez plutôt une ville.",
  attractionsLocationUnavailable: "La localisation n’est pas disponible sur cet appareil ou navigateur.",
  attractionsLoadingPhotos: "Chargement des photographies...",
  attractionsLoadingHistory: "Chargement des informations historiques...",
  attractionsServiceUnavailable: "Service d’attractions indisponible. Réessayez dans un moment.",
  attractionsWikipediaUnavailable: "Service Wikipédia indisponible.",
  attractionsImageUnavailable: "Service d’images indisponible.",
  attractionsNoLicensedImage: "Aucune photographie sous licence disponible",
  attractionsNoHistory: "Aucun résumé historique en anglais disponible",
  attractionsPhotoView: "Fiches avec photos",
  attractionsArchaeological: "Site archéologique",
  attractionsCastle: "Château, fort ou palais",
  attractionsZoo: "Zoo ou aquarium",
  attractionsTheme: "Parc à thème",
  attractionsArtwork: "Œuvre d’art publique",
  attractionsCultural: "Attraction culturelle",
  attractionsOther: "Autre attraction cartographiée",
  attractionsPhotoAvailable: "Photographie disponible",
  attractionsHistoryAvailable: "Résumé historique en anglais disponible",
  attractionsSortCategory: "Catégorie",
  attractionsSortPhoto: "Photographies disponibles en premier",
  attractionsSortHistory: "Résumés historiques disponibles en premier",
  attractionsSortComplete: "Informations les plus complètes",
  attractionsInfoSource: "Source des informations",
  attractionsSave: "Ajouter aux favoris",
  attractionsSaved: "Enregistré",
};
