export const frenchTransportLabelsA: Record<string, string> = {
  carRentalTitle: "Location de voitures",
  carRentalSubtitle: "Trouvez des agences de location de voitures cartographiées avec leurs coordonnées officielles lorsque les données les fournissent.",
  carRentalOpen: "Location de voitures",
  carRentalBack: "Retour au planificateur",
  carRentalNotice: "Les informations sur les agences proviennent de données cartographiques contributives et peuvent être incomplètes ou obsolètes. Confirmez directement auprès de l’agence l’emplacement, les horaires, les conditions, le prix, l’assurance, la caution et la disponibilité des véhicules.",
  carRentalAvailabilityNotice: "La présence d’une agence dans les résultats ne signifie pas que des véhicules sont actuellement disponibles.",
  carRentalLiveNotice: "Cette recherche cartographique ne fournit ni prix en direct ni disponibilité des véhicules. Contactez l’agence ou consultez son site officiel pour confirmer la disponibilité et le prix final.",
  carRentalUseLocation: "Utiliser ma position",
  carRentalManualSearch: "Rechercher une ville, un aéroport ou une gare",
  carRentalManualPlaceholder: "Ville, aéroport, gare ferroviaire...",
  carRentalSearchNear: "Rechercher près de",
  carRentalDestinationSearch: "Destination",
  carRentalAirportSearch: "Aéroport",
  carRentalStationSearch: "Gare ferroviaire ou routière",
  carRentalSearch: "Rechercher",
  carRentalSearchThisArea: "Rechercher dans cette zone",
  carRentalRecentre: "Recentrer sur ma position",
  carRentalFitResults: "Afficher tous les résultats",
  carRentalRadius: "Rayon",
  carRentalRequestingLocation: "Demande de localisation...",
  carRentalSearching: "Recherche d’agences de location cartographiées...",
  carRentalLocationDenied: "L’autorisation de localisation a été refusée. Recherchez plutôt une destination.",
  carRentalLocationUnavailable: "La localisation n’est pas disponible sur cet appareil ou navigateur.",
  carRentalServiceUnavailable: "Service de données cartographiques indisponible. Réessayez dans un moment.",
  carRentalTimedOut: "La recherche a expiré. Essayez un rayon plus petit ou réessayez.",
  carRentalTooMany: "Trop de résultats. Essayez un rayon plus petit.",
  carRentalOffline: "Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.",
  carRentalCached: "Affichage des agences de location mises en cache.",
  carRentalNoResults: "Aucune agence de location cartographiée n’a été trouvée dans cette zone. Cela ne signifie pas nécessairement qu’il n’en existe aucune.",
  carRentalRetry: "Réessayer",
  carRentalIncreaseRadius: "Augmenter le rayon",
  carRentalSearchAnother: "Rechercher une autre destination",
  carRentalMapView: "Carte",
  carRentalListView: "Liste à proximité",
  carRentalAllOffices: "Toutes les agences",
  carRentalAirportOffice: "Agence de location à l’aéroport",
  carRentalCityOffice: "Agence de location en ville",
  carRentalRailwayOffice: "Agence de location en gare ferroviaire",
  carRentalBusOffice: "Agence de location en gare routière",
  carRentalHotelDesk: "Comptoir de location dans un hôtel ou un lieu public",
  carRentalIndependentOffice: "Agence locale indépendante",
  carRentalUnknownOffice: "Type d’emplacement inconnu",
  carRentalAtAirport: "À l’aéroport ou à proximité",
  carRentalWebsiteAvailable: "Site officiel disponible",
  carRentalPhoneAvailable: "Téléphone disponible",
  carRentalSort: "Trier",
  carRentalSortAirport: "Agences d’aéroport en premier",
  carRentalSortWebsite: "Site officiel disponible",
  carRentalLegend: "Légende des marqueurs",
  carRentalBrand: "Marque",
  carRentalOperator: "Exploitant",
  carRentalLocationType: "Type d’emplacement",
  carRentalLocationContext: "Aéroport ou gare",
  carRentalEmail: "E-mail",
  carRentalBookingWebsite: "Site officiel de réservation",
  carRentalBranchRef: "Référence de l’agence",
  carRentalOfficialWebsiteListed: "Site officiel indiqué dans les données cartographiques",
  carRentalOfficialBookingListed: "Site officiel de réservation indiqué dans les données cartographiques",
  carRentalOpenOfficialWebsite: "Ouvrir le site officiel",
  carRentalCallOffice: "Appeler l’agence",
  carRentalChecklistTitle: "À confirmer directement avant de réserver",
  carRentalChecklistIntro: "Cette recherche cartographique ne fournit pas de conseils juridiques propres à chaque pays.",
  carRentalCheckAge: "Âge minimum du conducteur",
  carRentalCheckLicence: "Exigences relatives au permis de conduire valide",
  carRentalCheckPermit: "Exigences relatives au permis de conduire international",
  carRentalCheckDeposit: "Exigences relatives à la caution et au moyen de paiement",
  carRentalCheckInsurance: "Couverture d’assurance et exclusions",
  carRentalCheckFuel: "Politique de carburant",
  carRentalCheckMileage: "Limites de kilométrage",
  carRentalCheckDriver: "Frais de conducteur supplémentaire",
  carRentalCheckBorder: "Restrictions de franchissement des frontières",
  carRentalCheckCancel: "Politique d’annulation",
  carRentalCheckTimes: "Heures de prise en charge et de restitution",
  carRentalCheckLate: "Frais de restitution tardive",
};
