export const frenchLabels: Record<string, string> = {
  title: 'SafarOne',
  subtitle: 'Planificateur de voyage musulman',
  tagline: 'Planifiez avec foi. Voyagez en paix.',
  prototype: '',
  language: 'Langue',
  city: 'Ville',
  cityAutocomplete: 'Saisie automatique de la ville',
  cityPlaceholder: 'N’importe quelle ville',
  region: 'Région',
  allRegions: 'Toutes les régions',
  startDate: 'Date de début',
  endDate: 'Date de fin',
  startHour: 'Disponible à partir de',
  endHour: 'Jusqu’à',
  groupSize: 'Taille du groupe',
  budget: 'Budget',
  interests: 'Centres d’intérêt',
  walkingAbility: 'Capacité de marche',
  transportation: 'Transport',
  prayerMethod: 'Méthode de calcul des prières',
  prayerPreference: 'Préférence de prière',
  children: 'Enfants',
  womenPrayerRequired: 'Espace de prière pour femmes requis',
  wuduRequired: 'Ablutions requises',
  accessibilityNeeds: 'Besoins d’accessibilité',
  halalPreference: 'Préférence alimentaire halal',
  plan: 'Créer l’itinéraire',
  replan: 'Replanifier à partir d’ici',
  sample: 'Données d’exemple uniquement. Vérifiez les heures de prière, les équipements des mosquées, les horaires d’ouverture et les affirmations halal avant le voyage.',
  legend: 'Libellés d’information',
  formAria: 'Préférences du planificateur',
  prayerWindowsAre: 'Créneaux de prière',
  transportEstimatesAre: 'Temps de trajet estimés',
  walking: 'à pied',
  publicTransport: 'transports en commun',
  taxi: 'taxi',
  minutesShort: 'min',
  evidenceNote: 'Note sur la source',
  women: 'Femmes',
  wudu: 'Ablutions',
  accessibility: 'Accessibilité',
  facilityInfoMayBeIncomplete: 'Les informations sur les équipements peuvent être incomplètes',
  facilityAvailable: 'Disponible',
  facilityInfoUnavailable: 'Information indisponible',
  facilityEstimatedInfo: 'Information estimée',
  emptyState: 'Aucun élément d’itinéraire pour le moment. Choisissez vos préférences et créez un itinéraire.',
  generatePrompt: 'Choisissez votre destination et vos préférences, puis appuyez sur Créer l’itinéraire.',
  itineraryReady: 'Itinéraire créé.',
  homeTripsGroup: 'Vos voyages',
  homeEssentialsGroup: 'Essentiels musulmans',
  homeTravelToolsGroup: 'Outils de voyage',
  savedTripsTitle: 'Voyages enregistrés',
  savedTripsSubtitle: 'Rouvrez les itinéraires enregistrés localement sur cet appareil.',
  savedTripsOpen: 'Voyages enregistrés',
  savedTripsBack: 'Retour au planificateur',
  saveTrip: 'Enregistrer le voyage',
  saveChanges: 'Enregistrer les modifications',
  savedLocally: 'Enregistré localement sur cet appareil',
  noCloudSync: 'Aucune synchronisation cloud',
  unsavedChanges: 'Modifications non enregistrées',
  saveFailed: 'Échec de l’enregistrement. Le stockage peut être bloqué ou plein.',
  savedStatus: 'Enregistré',
  renameTrip: 'Renommer',
  duplicateTrip: 'Dupliquer',
  deleteTrip: 'Supprimer',
  reopenTrip: 'Rouvrir',
  savedTripsEmpty: 'Aucun voyage enregistré. Créez un itinéraire, puis choisissez Enregistrer le voyage.',
  deleteTripConfirm: 'Supprimer le voyage enregistré',
  tripName: 'Nom du voyage',
  tripSummary: 'Résumé du voyage',
  tripDates: 'Dates du voyage',
  tripDays: 'Jours',
  tripGroup: 'Groupe',
  tripStyle: 'Style',
  editPlan: 'Modifier le plan',
  shareTrip: 'Partager le voyage',
  copyItinerary: 'Copier l’itinéraire',
  exportCalendar: 'Exporter le calendrier',
  printItinerary: 'Imprimer / Enregistrer en PDF',
  itineraryCopied: 'Itinéraire copié.',
  calendarDownloaded: 'Calendrier téléchargé.',
  sharingUnavailable: 'Le partage n’est pas disponible ici. Vous pouvez copier l’itinéraire.',
  shareCancelled: 'Partage annulé.',
  unableToShare: 'Impossible de partager.',
  shareLiveInfoWarning: 'Les cartes, la météo, les taux de change, les horaires et les sites externes peuvent nécessiter Internet et doivent être vérifiés à nouveau.',
  savedSnapshotLabel: 'Instantané de l’itinéraire enregistré',
  reportProblem: 'Signaler un problème',
  reportWhatWrong: 'Quel est le problème ?',
  reportWrongName: 'Nom incorrect',
  reportWrongLocation: 'Emplacement incorrect',
  reportClosed: 'Lieu fermé ou supprimé',
  reportWrongCategory: 'Catégorie incorrecte',
  reportHours: 'Horaires incorrects',
  reportContact: 'Téléphone ou site incorrect',
  reportAccessibility: 'Informations d’accessibilité incorrectes',
  reportHalal: 'Informations halal incorrectes',
  reportOther: 'Autre',
  reportOptionalNote: 'Note facultative',
  reportOpenSource: 'Ouvrir la fiche source',
  reportOsm: 'Signaler ou corriger sur OpenStreetMap',
  reportOsmAccount: 'Un compte OpenStreetMap peut être requis.',
  reportAppProblem: 'Signaler un problème de l’application',
  reportGithubAccount: 'Un compte GitHub peut être requis.',
  reportCopy: 'Copier les détails du signalement',
  reportShare: 'Partager les détails du signalement',
  reportCopied: 'Signalement copié.',
  reportCopyFailed: 'Impossible de copier.',
  reportExternalNotice: 'L’ouverture de la page externe n’envoie pas automatiquement le signalement.',
  reportClose: 'Fermer',
  privacyPolicy: 'Politique de confidentialité',
  supportPage: 'Assistance',
  developerCredit: 'Développé par Firas Badran',
  supportEmailLabel: 'Assistance : planetearthkh@gmail.com',
  travelDetails: 'Détails du voyage',
  travelOptional: 'Détails facultatifs du voyage',
  travelAddDetail: 'Ajouter un détail',
  travelChooseType: 'Choisir le type de détail',
  travelDetailFlight: 'Vol',
  travelDetailAccommodation: 'Hébergement',
  travelDetailReservation: 'Réservation',
  travelDetailContact: 'Contact du prestataire',
  travelAirline: 'Compagnie aérienne',
  travelFlightNumber: 'Numéro de vol',
  travelDepartureAirport: 'Aéroport de départ',
  travelArrivalAirport: 'Aéroport d’arrivée',
  travelDepartureDateTime: 'Date et heure de départ',
  travelArrivalDateTime: 'Date et heure d’arrivée',
  travelDepartureTimeZone: 'Fuseau horaire de départ',
  travelArrivalTimeZone: 'Fuseau horaire d’arrivée',
  travelPropertyName: 'Nom de l’établissement',
  travelAddress: 'Adresse',
  travelCheckIn: 'Arrivée',
  travelCheckOut: 'Départ',
  travelTimeZone: 'Fuseau horaire',
  travelReservationTitle: 'Titre de la réservation',
  travelProvider: 'Prestataire',
  travelStartDateTime: 'Date et heure de début',
  travelEndDateTime: 'Date et heure de fin',
  travelMeetingPoint: 'Adresse ou point de rendez-vous',
  travelProviderContactName: 'Nom du prestataire ou du contact',
  travelRole: 'Rôle ou service',
  travelPhone: 'Numéro de téléphone',
  travelWebsite: 'Site web',
  travelBookingReference: 'Référence de réservation',
  travelPrivateReference: 'Privé — exclu du partage et de l’export du calendrier',
  travelPrivateReferenceExport: 'Les références privées sont stockées uniquement sur cet appareil et ne sont pas incluses.',
  travelNotes: 'Notes',
  travelSave: 'Enregistrer',
  travelCancel: 'Annuler',
  travelEdit: 'Modifier',
  travelDelete: 'Supprimer',
  travelDeleteConfirm: 'Supprimer ce détail ?',
  travelDetailAdded: 'Détail ajouté.',
  travelDetailUpdated: 'Détail mis à jour.',
  travelDetailDeleted: 'Détail supprimé.',
  travelInvalidDate: 'Date ou heure invalide.',
  travelEndAfterStart: 'La fin doit être postérieure au début.',
  travelInvalidTimeZone: 'Fuseau horaire invalide.',
  travelInvalidWebsite: 'Site web invalide.',
  travelRequiredFields: 'Remplissez les champs obligatoires.',
  travelStoredOnly: 'Stocké uniquement sur cet appareil',
  travelStorageNotEncrypted: 'Le stockage du navigateur n’est pas chiffré',
  travelClearingData: 'La suppression des données du navigateur peut effacer ces détails',
  travelSensitiveWarning: 'Ne saisissez pas de passeport, carte bancaire, mot de passe ou document d’identité',
  travelNoDetails: 'Aucun détail de voyage ajouté.',
  travelEmptyDescription: 'Les détails du voyage sont facultatifs et utiles hors ligne pour votre itinéraire enregistré.',
  approximateQibla: 'Direction approximative de la Qibla depuis le centre-ville',
  savedAt: 'Enregistré',
  storageRecovered: 'Le stockage des voyages n’a pas pu être lu. Les voyages valides existants n’ont pas été modifiés.',
  offlineIndicator: 'Hors ligne — les voyages enregistrés restent disponibles',
  onlineIndicator: 'De nouveau en ligne',
  internetRequired: 'Une connexion Internet est requise pour les outils en direct.',
  offlineLimitNotice: 'Les itinéraires enregistrés sont disponibles hors ligne. Les cartes, la météo, les devises, les itinéraires routiers et les sites externes nécessitent Internet.',
  invalidEndDate: 'La date de fin ne peut pas précéder la date de début.',
  invalidEndTime: 'L’heure de fin ne peut pas précéder l’heure de début pour un voyage d’une journée.',
  invalidGroupSize: 'La taille du groupe doit être d’au moins 1.',
  invalidCity: 'Choisissez une ville prise en charge avant de créer un itinéraire.',
  invalidTripTooLong: 'Les voyages peuvent être planifiés jusqu’à 14 jours.',
  dayHeading: 'Jour',
  noCities: 'Aucune ville ne correspond encore à cette région.',
  cityStreetMap: 'Plan de la ville',
  openFullMap: 'Ouvrir la carte complète',
  findOnMap: 'Trouver sur la carte',
  mapUnavailable: 'Carte indisponible',
  available: 'Disponible',
  notAvailable: 'Indisponible',
  qibla: 'Qibla',
  qiblaTitle: 'Direction de la Qibla',
  qiblaSubtitle: 'Utilisez votre position pour vous orienter vers la Kaaba.',
  qiblaOpen: 'Ouvrir la Qibla',
  qiblaBack: 'Retour au planificateur',
  qiblaRequestLocation: 'Utiliser ma position',
  qiblaRequestMotion: 'Activer la boussole',
  qiblaRetry: 'Réessayer',
  qiblaLoadingLocation: 'Recherche de votre position...',
  qiblaLocationDenied: 'L’autorisation de localisation a été refusée. Activez-la ou réessayez.',
  qiblaLocationUnavailable: 'La localisation n’est pas disponible sur cet appareil ou navigateur.',
  qiblaMotionUnavailable: 'La boussole en direct est indisponible. Direction fixe affichée.',
  qiblaMotionDenied: 'L’autorisation de la boussole a été refusée. Direction fixe affichée.',
  qiblaLiveCompass: 'Boussole en direct active',
  qiblaFixedBearing: 'Direction fixe',
  qiblaBearing: 'Direction',
  qiblaLocation: 'Position',
  qiblaKaaba: 'Kaaba',
  qiblaNorth: 'N',
  qiblaEast: 'E',
  qiblaSouth: 'S',
  qiblaWest: 'O',
  qiblaDegrees: 'degrés',
  prayerSpacesTitle: 'Mosquées et espaces de prière',
  prayerSpacesSubtitle: 'Trouvez des mosquées cartographiées et des espaces de prière calmes près de vous ou de votre destination.',
  prayerSpacesOpen: 'Mosquées et espaces de prière',
  prayerSpacesBack: 'Retour au planificateur',
  prayerMapView: 'Carte',
  prayerListView: 'Liste à proximité',
  prayerUseLocation: 'Utiliser ma position',
  prayerManualSearch: 'Rechercher une ville ou une destination',
  prayerManualPlaceholder: 'Ville, aéroport, université, hôpital...',
  prayerSearch: 'Rechercher',
  prayerSearchThisArea: 'Rechercher dans cette zone',
  prayerRadius: 'Rayon',
  prayerRequestingLocation: 'Demande de localisation...',
  prayerSearching: 'Recherche sur OpenStreetMap...',
  prayerLocationDenied: 'L’autorisation de localisation a été refusée. Recherchez plutôt une ville ou une destination.',
  prayerLocationUnavailable: 'La localisation n’est pas disponible sur cet appareil ou navigateur.',
  prayerServiceUnavailable: 'Service de recherche indisponible. Réessayez dans un moment.',
  prayerNoResults: 'Aucun lieu trouvé à proximité.',
  prayerRetry: 'Réessayer',
  prayerIncreaseRadius: 'Augmenter le rayon de recherche',
  prayerNotice: 'Les informations peuvent être incomplètes ou obsolètes. Vérifiez l’accès et les horaires avant le voyage.',
  prayerAllPlaces: 'Tous les lieux',
  prayerMosques: 'Mosquées',
  prayerRooms: 'Salles de prière',
  prayerQuietSpaces: 'Espaces calmes',
  prayerOpenNow: 'Ouvert maintenant',
  prayerWomenArea: 'Espace de prière pour femmes',
  prayerWuduAvailable: 'Ablutions disponibles',
  prayerWheelchairAccessible: 'Accessible en fauteuil roulant',
  prayerSort: 'Trier',
  prayerNearest: 'Les plus proches',
  prayerName: 'Nom',
  prayerOpenNowSort: 'Ouvert maintenant',
  prayerTypeMosque: 'Mosquée',
  prayerTypeRoom: 'Salle de prière',
  prayerTypeQuiet: 'Espace de prière calme',
  prayerDistance: 'Distance',
  prayerAddress: 'Adresse',
  prayerOpeningHours: 'Horaires d’ouverture',
  prayerWomen: 'Espace de prière pour femmes',
  prayerWudu: 'Équipements d’ablutions',
  prayerWheelchair: 'Accessibilité en fauteuil roulant',
  prayerWebsite: 'Site web',
  prayerTelephone: 'Téléphone',
  prayerVerification: 'Statut de vérification',
  prayerVerified: 'Vérifié',
  prayerUnverified: 'Non vérifié',
  prayerUnknown: 'Non vérifié',
  prayerViewOnMap: 'Voir sur la carte',
  prayerDirections: 'Obtenir l’itinéraire',
  prayerAppleMaps: 'Plans Apple',
  prayerBrowserMap: 'Carte du navigateur',
  moneyTitle: 'Argent et devises',
  moneySubtitle: 'Convertissez votre budget avec des taux de référence mis en cache et des indications sur la devise locale.',
  moneyOpen: 'Argent et devises',
  moneyBack: 'Retour au planificateur',
  amount: 'Montant',
  fromCurrency: 'Devise source',
  toCurrency: 'Devise cible',
  searchCurrency: 'Rechercher des devises',
  swapCurrencies: 'Inverser les devises',
  clear: 'Effacer',
  refreshRates: 'Actualiser les taux',
  copyResult: 'Copier le résultat',
  pairRate: 'Taux actuel',
  reversePairRate: 'Taux inverse',
  rateDate: 'Date du taux',
  lastRefreshed: 'Dernière actualisation',
  destination: 'Destination',
  localCurrency: 'Devise locale',
  symbol: 'Symbole',
  popularCurrencies: 'Devises populaires',
  loadingCurrencies: 'Chargement des devises...',
  loadingRate: 'Chargement du taux de change...',
  rateUpdated: 'Taux mis à jour.',
  offline: 'Vous semblez être hors ligne.',
  cachedRate: 'Taux mis en cache',
  serviceUnavailable: 'Service de taux indisponible.',
  unsupportedCurrency: 'Paire de devises non prise en charge.',
  invalidAmount: 'Saisissez un montant valide et non négatif.',
  noCachedData: 'Aucun taux mis en cache n’est disponible.',
  retry: 'Réessayer',
  sameCurrency: 'La même devise est sélectionnée ; aucun taux de change n’est nécessaire.',
  rateNotice: 'Les taux de change sont indicatifs et peuvent différer de ceux des banques, cartes, hôtels ou bureaux de change. Vérifiez le taux final et les frais avant de payer.',
  moneyInfo: 'Informations financières pour le voyageur',
  officialCurrency: 'Devise officielle ou locale',
  denominations: 'Coupures courantes',
  cardsAccepted: 'Cartes généralement acceptées',
  paymentWarning: 'Ne vous fiez pas à des généralisations non vérifiées ; confirmez les options de paiement locales avant le voyage.',
  rateHistory: 'Historique du taux',
  sevenDays: '7 jours',
  thirtyDays: '30 jours',
  ninetyDays: '90 jours',
  highestRate: 'Taux le plus élevé',
  lowestRate: 'Taux le plus bas',
  startRate: 'Taux initial',
  latestRate: 'Dernier taux',
  percentageChange: 'Variation en pourcentage',
  copied: 'Copié.',
  halalRestaurantsTitle: 'Restaurants halal',
  halalRestaurantsSubtitle: 'Trouvez des restaurants cartographiés avec des indications halal explicites près de vous ou de votre destination.',
  halalRestaurantsOpen: 'Restaurants halal',
  halalRestaurantsBack: 'Retour au planificateur',
  halalNotice: 'Les informations proviennent de données cartographiques contributives et peuvent être incomplètes ou obsolètes. Confirmez directement le statut halal, la certification, les horaires et le menu.',
  halalMeaningNotice: 'Halal uniquement signifie que les données indiquent que toute la nourriture est halal. Options halal signifie que seuls certains articles peuvent être halal.',
  halalUseLocation: 'Utiliser ma position',
  halalManualSearch: 'Rechercher une ville ou une destination',
  halalManualPlaceholder: 'Ville, quartier, aéroport...',
  halalSearch: 'Rechercher',
  halalSearchThisArea: 'Rechercher dans cette zone',
  halalRecentre: 'Recentrer sur ma position',
  halalFitResults: 'Afficher tous les résultats',
  halalRadius: 'Rayon',
  halalRequestingLocation: 'Demande de localisation...',
  halalSearching: 'Recherche de restaurants halal cartographiés...',
  halalLocationDenied: 'L’autorisation de localisation a été refusée. Recherchez plutôt une ville ou une destination.',
  halalLocationUnavailable: 'La localisation n’est pas disponible sur cet appareil ou navigateur.',
  halalServiceUnavailable: 'Service de données cartographiques indisponible. Réessayez dans un moment.',
  halalTimedOut: 'La recherche a expiré. Essayez un rayon plus petit ou réessayez.',
  halalTooMany: 'Trop de résultats. Essayez un rayon plus petit.',
  halalNoResults: 'Aucun restaurant halal cartographié n’a été trouvé dans cette zone. Cela ne signifie pas nécessairement qu’il n’en existe aucun.',
  halalNoReliable: 'Aucun résultat avec indication halal fiable ne correspond à ces filtres.',
  halalCached: 'Affichage des résultats de restaurants mis en cache.',
  halalOffline: 'Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.',
  halalRetry: 'Réessayer',
  halalIncreaseRadius: 'Augmenter le rayon',
  halalSearchAnotherCity: 'Rechercher une autre ville',
  halalMapView: 'Carte',
  halalListView: 'Liste à proximité',
  halalAllReliable: 'Tous les résultats fiables',
  halalOnly: 'Halal uniquement',
  halalOptions: 'Options halal',
  halalCertificationListed: 'Certification indiquée',
  halalLegacy: 'Ancienne indication halal',
  halalPossible: 'Possible / non vérifié',
  halalRestaurant: 'Restaurant',
  halalFastFood: 'Restauration rapide',
  halalCafe: 'Café',
  halalFoodCourt: 'Aire de restauration',
  halalOpenNow: 'Ouvert maintenant',
  halalTakeaway: 'À emporter',
  halalDelivery: 'Livraison',
  halalWheelchair: 'Accessible en fauteuil roulant',
  halalCuisine: 'Cuisine',
  halalAllCuisines: 'Toutes les cuisines',
  halalSort: 'Trier',
  halalNearest: 'Les plus proches',
  halalSortName: 'Nom',
  halalSortStatus: 'Statut halal',
  halalSortOpen: 'Ouvert maintenant',
  halalSortCuisine: 'Cuisine',
  halalCertificationNotice: 'Certification indiquée dans les données source',
  halalLegacyNotice: 'Ancienne indication non vérifiée',
  halalPossibleNotice: 'Mention halal possible dans les données source ; confirmez directement.',
  halalOpeningUnavailable: 'Statut d’ouverture indisponible',
  halalOpen: 'Ouvert maintenant',
  halalClosed: 'Fermé actuellement',
  halalCuisineLabel: 'Cuisine',
  halalMenu: 'Menu',
  halalPrice: 'Niveau de prix',
  halalOutdoor: 'Places en extérieur',
  halalInfoIssue: 'Information incorrecte ou manquante ?',
  halalCopyDetails: 'Copier les détails',
  halalCopiedDetails: 'Détails copiés.',
  halalLegend: 'Légende des marqueurs',
  weatherTitle: 'Météo',
  weatherSubtitle: 'Consultez les conditions actuelles, les prévisions horaires et les indicateurs météo pour votre destination.',
  weatherOpen: 'Météo',
  weatherBack: 'Retour au planificateur',
  weatherNotice: 'Les prévisions peuvent changer et différer des conditions locales. Consultez les services météorologiques officiels pour les alertes importantes.',
  weatherTravelNotice: 'Ces indicateurs reposent sur les prévisions et ne sont pas des alertes officielles. Suivez les autorités locales et les services météo officiels.',
  weatherAttribution: 'Données météo par Open-Meteo',
  weatherUseLocation: 'Utiliser ma position',
  weatherUseDestination: 'Utiliser la destination du voyage',
  weatherManualSearch: 'Rechercher une autre ville',
  weatherManualPlaceholder: 'Ville ou destination...',
  weatherRecentDestinations: 'Destinations récentes',
  weatherSearch: 'Rechercher',
  weatherRefresh: 'Actualiser',
  weatherRetry: 'Réessayer',
  weatherSearchAnother: 'Rechercher une autre ville',
  weatherRequestingLocation: 'Demande de localisation...',
  weatherLocationDenied: 'L’autorisation de localisation a été refusée. Recherchez manuellement.',
  weatherLocationUnavailable: 'La localisation n’est pas disponible sur cet appareil ou navigateur.',
  weatherLoading: 'Chargement de la météo...',
  weatherUpdated: 'Mis à jour à l’instant.',
  weatherCached: 'Météo mise en cache',
  weatherOffline: 'Vous semblez être hors ligne. Affichage de la météo mise en cache si disponible.',
  weatherUnavailable: 'Service météo indisponible. Réessayez dans un moment.',
  weatherTimedOut: 'La demande météo a expiré.',
  weatherInvalid: 'Réponse météo invalide.',
  weatherNoCached: 'Aucune météo mise en cache pour cet emplacement.',
  weatherUnsupported: 'Emplacement non pris en charge.',
  weatherCurrent: 'Météo actuelle',
  weatherHourly: 'Prévisions horaires',
  weatherNoLaterHourly: 'Aucune prévision horaire ultérieure n’est disponible.',
  weatherDaily: 'Prévisions sur 7 jours',
  weatherTravel: 'Conditions de voyage',
  weatherPacking: 'Conseils généraux selon la météo',
  weatherPrayer: 'Météo autour des heures de prière',
  weatherUnits: 'Unités',
  weatherTempUnit: 'Température',
  weatherWindUnit: 'Vent',
  weatherPrecipUnit: 'Précipitations',
  weatherCelsius: 'Celsius',
  weatherFahrenheit: 'Fahrenheit',
  weatherKmh: 'km/h',
  weatherMph: 'mph',
  weatherMs: 'm/s',
  weatherKnots: 'nœuds',
  weatherMm: 'millimètres',
  weatherInch: 'pouces',
  weatherCondition: 'Conditions',
  weatherFeelsLike: 'Ressenti',
  weatherHighLow: 'Max. / min.',
  weatherHumidity: 'Humidité',
  weatherWind: 'Vent',
  weatherGusts: 'Rafales',
  weatherCloud: 'Couverture nuageuse',
  weatherUv: 'Indice UV',
  weatherVisibility: 'Visibilité',
  weatherValueUnavailable: 'Indisponible',
  weatherSunrise: 'Lever du soleil',
  weatherSunset: 'Coucher du soleil',
  weatherDayNight: 'Jour / nuit',
  weatherLastUpdated: 'Dernière mise à jour',
  weatherRainSnow: 'Pluie ou neige',
  weatherExpand48: 'Afficher 48 heures',
  weatherShow24: 'Afficher 24 heures',
  weatherLocalTime: 'Heure locale',
  weatherTimezone: 'Fuseau horaire',
  weatherCoordinates: 'Coordonnées',
  weatherDaylight: 'Jour',
  weatherNight: 'Nuit',
  weatherClear: 'Ciel dégagé',
  weatherMainlyClear: 'Généralement dégagé',
  weatherPartlyCloudy: 'Partiellement nuageux',
  weatherOvercast: 'Couvert',
  weatherFog: 'Brouillard',
  weatherDrizzle: 'Bruine',
  weatherRain: 'Pluie',
  weatherFreezingRain: 'Pluie verglaçante',
  weatherSnow: 'Neige',
  weatherSnowShowers: 'Averses de neige',
  weatherRainShowers: 'Averses de pluie',
  weatherThunderstorm: 'Orage',
  weatherThunderstormHail: 'Orage avec grêle',
  weatherUnknown: 'Conditions inconnues',
  weatherIndicatorRain: 'Pluie probable',
  weatherIndicatorSnow: 'Neige possible',
  weatherIndicatorWind: 'Vent fort',
  weatherIndicatorUv: 'UV élevé',
  weatherIndicatorVisibility: 'Faible visibilité',
  weatherIndicatorHot: 'Conditions très chaudes',
  weatherIndicatorCold: 'Conditions froides',
  weatherIndicatorThunderstorm: 'Risque d’orage',
  weatherPackUmbrella: 'Emportez un parapluie',
  weatherPackJacket: 'Prenez une veste légère',
  weatherPackCold: 'Préparez-vous au froid',
  weatherPackSun: 'Utilisez une protection solaire',
  weatherPackFootwear: 'Portez des chaussures adaptées à la pluie ou à la neige',
  weatherPackWater: 'Emportez de l’eau par temps chaud',
  attractionsTitle: 'Attractions',
  attractionsOpen: 'Attractions',
  attractionsBack: 'Retour au planificateur',
  attractionsUseLocation: 'Utiliser ma position',
  attractionsUseDestination: 'Utiliser la destination du voyage',
  attractionsManualSearch: 'Rechercher une autre ville',
  attractionsSearch: 'Rechercher',
  attractionsSearchAnother: 'Rechercher une autre destination',
  attractionsRequestingLocation: 'Demande de localisation...',
  attractionsSearching: 'Recherche d’attractions cartographiées...',
  attractionsTimedOut: 'La recherche d’attractions a pris trop de temps. Essayez un rayon plus petit ou réessayez.',
  attractionsOffline: 'Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.',
  attractionsCached: 'Affichage des attractions mises en cache.',
  attractionsNoResults: 'Aucune attraction cartographiée n’a été trouvée dans cette zone.',
  attractionsMapView: 'Carte',
  attractionsListView: 'Liste à proximité',
  attractionsAll: 'Toutes les attractions',
  attractionsHistoric: 'Sites historiques',
  attractionsMuseum: 'Musées',
  attractionsGallery: 'Galeries d’art',
  attractionsMonument: 'Monuments et mémoriaux',
  attractionsReligious: 'Patrimoine religieux',
  attractionsViewpoint: 'Points de vue',
  attractionsNatural: 'Attractions naturelles',
  attractionsPark: 'Parcs et jardins',
  attractionsCategory: 'Catégorie',
  attractionsAdmission: 'Entrée',
  attractionsDetails: 'Détails',
  attractionsClose: 'Fermer les détails',
  attractionsReadMore: 'Lire la suite sur Wikipédia',
};
