export const frenchTransportLabelsB: Record<string, string> = {
  publicTransportTitle: "Transports en commun",
  publicTransportSubtitle: "Trouvez les gares, stations de métro, arrêts de tramway, gares routières et terminaux de ferry à proximité, avec les itinéraires et les informations disponibles.",
  publicTransportOpen: "Transports en commun",
  publicTransportBack: "Retour au planificateur",
  publicTransportNotice: "Les informations sur les transports en commun proviennent de données cartographiques ouvertes et contributives et peuvent être incomplètes ou obsolètes. Confirmez les lignes, les horaires, les tarifs et l’accessibilité auprès de l’exploitant officiel.",
  publicTransportLiveNotice: "Les départs en direct et la planification d’itinéraires ne sont pas encore disponibles.",
  publicTransportUseLocation: "Utiliser ma position",
  publicTransportUseDestination: "Utiliser la destination du voyage",
  publicTransportManualSearch: "Rechercher une autre ville",
  publicTransportManualPlaceholder: "Ville ou destination...",
  publicTransportSearch: "Rechercher",
  publicTransportSearchThisArea: "Rechercher dans cette zone",
  publicTransportRecentre: "Recentrer la carte",
  publicTransportFitResults: "Afficher tous les résultats",
  publicTransportRadius: "Rayon",
  publicTransportRequestingLocation: "Demande de localisation...",
  publicTransportSearching: "Recherche de transports en commun cartographiés...",
  publicTransportLocationDenied: "L’autorisation de localisation a été refusée. Recherchez plutôt une destination.",
  publicTransportLocationUnavailable: "La localisation n’est pas disponible sur cet appareil ou navigateur.",
  publicTransportServiceUnavailable: "Service de données cartographiques indisponible. Réessayez dans un moment.",
  publicTransportTimedOut: "La recherche a expiré. Essayez un rayon plus petit ou réessayez.",
  publicTransportTooMany: "Trop de résultats. Essayez un rayon plus petit.",
  publicTransportOffline: "Vous semblez être hors ligne. Affichage des résultats mis en cache si disponibles.",
  publicTransportCached: "Affichage des résultats de transports en commun mis en cache.",
  publicTransportNoResults: "Aucun arrêt ni aucune station de transport en commun cartographié n’a été trouvé dans cette zone. Cela ne signifie pas nécessairement qu’il n’en existe aucun.",
  publicTransportRetry: "Réessayer",
  publicTransportIncreaseRadius: "Augmenter le rayon",
  publicTransportSearchAnother: "Rechercher une autre ville",
  publicTransportMapView: "Carte",
  publicTransportListView: "Liste à proximité",
  publicTransportAll: "Tous les transports en commun",
  publicTransportSort: "Trier",
  publicTransportLegend: "Légende des marqueurs",
  transportTrain: "Gare ferroviaire",
  transportMetro: "Station de métro",
  transportLightRail: "Station de métro léger",
  transportTram: "Arrêt de tramway",
  transportBusStation: "Gare routière",
  transportBusStop: "Arrêt de bus",
  transportFerry: "Terminal de ferry",
  transportOther: "Autre arrêt de transport en commun",
  transportType: "Type de transport",
  transportOperator: "Exploitant",
  transportNetwork: "Réseau",
  transportReference: "Référence",
  transportLines: "Lignes ou itinéraires",
  transportShelter: "Abri",
  transportSeating: "Sièges",
  transportToilets: "Toilettes",
  transportToiletsAvailable: "Toilettes disponibles",
  transportShelterAvailable: "Abri disponible",
  transportOfficialWebsite: "Site officiel",
  transportSortType: "Type de transport",
};
