// Corrections reviewed after the multilingual release audit. Product names
// such as Apple Maps intentionally remain untranslated.
export const indonesianLabelCorrections = {
  "halalOnly": "Hanya halal",
  "halalOptions": "Pilihan halal",
  "halalMeaningNotice": "“Hanya halal” berarti data peta menyatakan semua makanan halal. “Pilihan halal” berarti hanya sebagian menu yang mungkin halal."
};

export const malayLabelCorrections = {
  "savedTripsEmpty": "Belum ada perjalanan disimpan. Jana jadual perjalanan, kemudian pilih Simpan perjalanan.",
  "deleteTripConfirm": "Padam perjalanan disimpan",
  "savedSnapshotLabel": "Snapshot jadual perjalanan disimpan",
  "reportCopy": "Salin butiran laporan",
  "travelBookingReference": "Rujukan tempahan",
  "travelEmptyDescription": "Butiran perjalanan adalah pilihan dan berguna di luar talian untuk jadual perjalanan yang disimpan.",
  "storageRecovered": "Storan perjalanan yang disimpan tidak dapat dibaca. Perjalanan sah yang sedia ada tidak diubah.",
  "offlineIndicator": "Luar talian — perjalanan disimpan kekal tersedia",
  "offlineLimitNotice": "Rancangan disimpan tersedia di luar talian. Peta langsung, cuaca, kadar pertukaran, arah, dan laman luar memerlukan internet.",
  "invalidCity": "Pilih bandar yang disokong sebelum membuat jadual perjalanan.",
  "noCities": "Belum ada bandar yang sepadan dengan wilayah ini.",
  "cityStreetMap": "Peta jalan bandar",
  "findOnMap": "Cari di peta",
  "qiblaLocationDenied": "Kebenaran lokasi ditolak. Aktifkan akses lokasi atau cuba lagi.",
  "qiblaMotionUnavailable": "Kompas langsung tidak tersedia. Memaparkan arah kiblat tetap.",
  "qiblaMotionDenied": "Kebenaran kompas ditolak. Memaparkan arah kiblat tetap.",
  "flightBestEstimate": "Anggaran terbaik yang tersedia berdasarkan GPS langsung atau laluan penerbangan disimpan.",
  "flightUseTravelDetails": "Gunakan penerbangan disimpan daripada Butiran Perjalanan",
  "flightGpsDenied": "Kebenaran lokasi ditolak. Mod Anggaran Laluan tersedia luar talian.",
  "flightStorageRecovered": "Data penerbangan disimpan tidak dapat dibaca dan diabaikan.",
  "prayerManualSearch": "Cari bandar atau destinasi",
  "prayerLocationDenied": "Kebenaran lokasi ditolak. Cari dengan bandar atau destinasi.",
  "prayerServiceUnavailable": "Perkhidmatan carian tidak tersedia. Cuba lagi sebentar lagi.",
  "prayerNoResults": "Tiada tempat berdekatan ditemui.",
  "prayerIncreaseRadius": "Besarkan jejari carian",
  "prayerSort": "Susun",
  "prayerNearest": "Terdekat dahulu",
  "prayerWheelchair": "Akses kerusi roda",
  "moneySubtitle": "Tukar wang perjalanan dengan kadar rujukan disimpan dan cadangan mata wang destinasi.",
  "offline": "Anda nampaknya sedang luar talian.",
  "cachedRate": "Kadar pertukaran disimpan",
  "unsupportedCurrency": "Pasangan mata wang tidak disokong.",
  "noCachedData": "Tiada kadar pertukaran disimpan.",
  "officialCurrency": "Mata wang rasmi/setempat",
  "rateHistory": "Sejarah kadar pertukaran",
  "halalRestaurantsSubtitle": "Cari restoran yang ditandai secara jelas sebagai halal dalam data peta, berhampiran anda atau destinasi anda.",
  "halalMeaningNotice": "“Halal sahaja” bermaksud data peta menyatakan semua makanan adalah halal. “Pilihan halal” bermaksud hanya sebahagian menu mungkin halal.",
  "halalManualSearch": "Cari bandar atau destinasi",
  "halalLocationDenied": "Kebenaran lokasi ditolak. Cari dengan bandar atau destinasi.",
  "halalServiceUnavailable": "Perkhidmatan data peta tidak tersedia. Cuba lagi sebentar lagi.",
  "halalTimedOut": "Carian tamat tempoh. Cuba radius lebih kecil atau cuba semula.",
  "halalCached": "Memaparkan hasil restoran disimpan.",
  "halalOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "halalIncreaseRadius": "Besarkan jejari",
  "halalSearchAnotherCity": "Cari bandar lain",
  "halalOnly": "Halal sahaja",
  "halalOptions": "Pilihan halal",
  "halalSort": "Susun",
  "halalNearest": "Terdekat dahulu",
  "halalCertificationNotice": "Pensijilan disenaraikan dalam data sumber",
  "halalCopyDetails": "Salin butiran",
  "halalCopiedDetails": "Butiran telah disalin.",
  "halalLegend": "Petunjuk penanda",
  "carRentalAvailabilityNotice": "Kemunculan pejabat dalam hasil carian tidak bermakna kenderaan sedang tersedia.",
  "carRentalLocationDenied": "Kebenaran lokasi ditolak. Cari dengan destinasi.",
  "carRentalServiceUnavailable": "Perkhidmatan data peta tidak tersedia. Cuba lagi sebentar lagi.",
  "carRentalTimedOut": "Carian tamat tempoh. Cuba radius lebih kecil atau cuba semula.",
  "carRentalOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "carRentalCached": "Memaparkan hasil sewaan kereta yang disimpan.",
  "carRentalIncreaseRadius": "Besarkan jejari",
  "carRentalSearchAnother": "Cari destinasi lain",
  "carRentalAirportOffice": "Pejabat sewa kereta lapangan terbang",
  "carRentalCityOffice": "Pejabat sewa kereta bandar",
  "carRentalIndependentOffice": "Pejabat sewaan tempatan bebas",
  "carRentalWebsiteAvailable": "Laman web rasmi tersedia",
  "carRentalSort": "Susun",
  "carRentalSortAirport": "Pejabat lapangan terbang dahulu",
  "carRentalSortWebsite": "Laman web rasmi tersedia dahulu",
  "carRentalLegend": "Petunjuk penanda",
  "carRentalBrand": "Jenama",
  "carRentalEmail": "E-mel",
  "carRentalBookingWebsite": "Laman tempahan rasmi",
  "carRentalBranchRef": "Rujukan cawangan",
  "carRentalOfficialWebsiteListed": "Laman web rasmi disenaraikan dalam data peta",
  "carRentalOfficialBookingListed": "Laman tempahan rasmi disenaraikan dalam data peta",
  "carRentalOpenOfficialWebsite": "Buka laman web rasmi",
  "carRentalChecklistIntro": "Carian peta ini tidak memberikan nasihat undang-undang khusus bagi sesebuah negara.",
  "carRentalCheckAge": "Syarat umur pemandu",
  "carRentalCheckPermit": "Syarat Permit Memandu Antarabangsa",
  "carRentalCheckDeposit": "Syarat deposit dan kad pembayaran",
  "carRentalCheckInsurance": "Perlindungan dan pengecualian insurans",
  "carRentalCheckFuel": "Polisi bahan api",
  "carRentalCheckMileage": "Had perbatuan",
  "carRentalCheckDriver": "Fi pemandu tambahan",
  "carRentalCheckBorder": "Sekatan rentas sempadan",
  "carRentalCheckTimes": "Waktu pengambilan dan pemulangan",
  "carRentalCheckLate": "Fi pemulangan lewat",
  "publicTransportUseDestination": "Gunakan destinasi perjalanan",
  "publicTransportManualSearch": "Cari bandar lain",
  "publicTransportSearching": "Mencari lokasi pengangkutan awam yang dipetakan...",
  "publicTransportLocationDenied": "Kebenaran lokasi ditolak. Cari dengan destinasi.",
  "publicTransportServiceUnavailable": "Perkhidmatan data peta tidak tersedia. Cuba lagi sebentar lagi.",
  "publicTransportTimedOut": "Carian tamat tempoh. Cuba radius lebih kecil atau cuba semula.",
  "publicTransportOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "publicTransportCached": "Memaparkan hasil pengangkutan awam yang disimpan.",
  "publicTransportNoResults": "Tiada perhentian atau stesen pengangkutan awam yang dipetakan ditemui di kawasan ini. Ini tidak semestinya bermakna tiada perkhidmatan di kawasan tersebut.",
  "publicTransportIncreaseRadius": "Besarkan jejari",
  "publicTransportSearchAnother": "Cari bandar lain",
  "publicTransportSort": "Susun",
  "taxiUseDestination": "Gunakan destinasi perjalanan",
  "taxiManualSearch": "Cari bandar lain",
  "taxiSearching": "Mencari perkhidmatan teksi yang dipetakan...",
  "taxiLocationDenied": "Kebenaran lokasi ditolak. Cari dengan destinasi.",
  "taxiServiceUnavailable": "Perkhidmatan data peta tidak tersedia. Cuba lagi sebentar lagi.",
  "taxiTimedOut": "Carian tamat tempoh. Cuba radius lebih kecil atau cuba semula.",
  "taxiOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "taxiCached": "Memaparkan hasil teksi yang disimpan.",
  "taxiNoResults": "Tiada pangkalan atau pejabat teksi yang dikenal pasti ditemui di kawasan ini. Ini tidak semestinya bermakna tiada perkhidmatan teksi di kawasan tersebut.",
  "taxiIncreaseRadius": "Besarkan jejari",
  "taxiSearchAnother": "Cari bandar lain",
  "taxiAll": "Semua perkhidmatan teksi",
  "taxiOther": "Perkhidmatan teksi dipetakan lain",
  "taxiSort": "Susun",
  "taxiSortType": "Jenis perkhidmatan teksi",
  "taxiType": "Jenis perkhidmatan teksi",
  "taxiCapacity": "Kapasiti",
  "taxiCall": "Hubungi perkhidmatan teksi",
  "weatherUseDestination": "Gunakan destinasi perjalanan",
  "weatherManualSearch": "Cari bandar lain",
  "weatherSearchAnother": "Cari bandar lain",
  "weatherLocationDenied": "Kebenaran lokasi ditolak. Cari manual sebaliknya.",
  "weatherCached": "Cuaca yang disimpan",
  "weatherOffline": "Anda nampaknya sedang luar talian. Cuaca yang disimpan dipaparkan jika tersedia.",
  "weatherUnavailable": "Perkhidmatan cuaca tidak tersedia. Cuba lagi sebentar lagi.",
  "weatherTimedOut": "Permintaan cuaca tamat tempoh.",
  "weatherInvalid": "Respons cuaca tidak sah.",
  "weatherNoCached": "Tiada data cuaca yang disimpan untuk lokasi ini.",
  "weatherUnsupported": "Lokasi tidak disokong.",
  "weatherNoLaterHourly": "Ramalan jam berikutnya tidak tersedia.",
  "weatherUnits": "Unit",
  "weatherTimezone": "Zon waktu",
  "weatherIndicatorRain": "Hujan mungkin berlaku",
  "weatherIndicatorVisibility": "Jarak penglihatan rendah",
  "attractionsPhotoNotice": "Foto hanya dipaparkan apabila terdapat padanan yang dipercayai dan lesen yang membenarkan penggunaan semula.",
  "attractionsUseDestination": "Gunakan destinasi perjalanan",
  "attractionsManualSearch": "Cari bandar lain",
  "attractionsSearchAnother": "Cari destinasi lain",
  "attractionsLocationDenied": "Kebenaran lokasi ditolak. Cari dengan bandar sebaliknya.",
  "attractionsSearching": "Mencari tarikan yang dipetakan...",
  "attractionsServiceUnavailable": "Perkhidmatan tarikan tidak tersedia. Cuba lagi sebentar lagi.",
  "attractionsWikipediaUnavailable": "Perkhidmatan Wikipedia tidak tersedia.",
  "attractionsImageUnavailable": "Perkhidmatan imej tidak tersedia.",
  "attractionsTimedOut": "Carian tarikan terlalu lama. Cuba radius yang lebih kecil atau cuba semula.",
  "attractionsOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "attractionsCached": "Memaparkan hasil tarikan yang disimpan.",
  "attractionsNoResults": "Tiada tarikan yang dipetakan ditemui di kawasan ini. Ini tidak semestinya bermakna tiada tarikan di kawasan tersebut.",
  "attractionsHistoric": "Tapak bersejarah",
  "attractionsArchaeological": "Laman arkeologi",
  "attractionsReligious": "Laman warisan agama",
  "attractionsArtwork": "Karya seni awam",
  "attractionsOther": "Tarikan dipetakan lain",
  "attractionsHistoryAvailable": "Sejarah dalam bahasa Inggeris tersedia",
  "attractionsSortPhoto": "Foto tersedia dahulu",
  "attractionsSortHistory": "Sejarah tersedia dahulu",
  "attractionsDetails": "Butiran",
  "attractionsClose": "Tutup butiran",
  "attractionsSave": "Simpan ke kegemaran",
  "attractionsReadMore": "Baca selanjutnya di Wikipedia",
  "toiletsManualSearch": "Cari bandar atau destinasi",
  "toiletsSearching": "Mencari tandas yang dipetakan...",
  "toiletsLocationDenied": "Kebenaran lokasi ditolak. Cari dengan bandar atau destinasi.",
  "toiletsServiceUnavailable": "Perkhidmatan data peta tidak tersedia. Cuba lagi sebentar lagi.",
  "toiletsTimedOut": "Carian tamat tempoh. Cuba radius lebih kecil atau cuba semula.",
  "toiletsOffline": "Anda nampaknya sedang luar talian. Memaparkan hasil disimpan jika ada.",
  "toiletsCached": "Memaparkan hasil tandas yang disimpan.",
  "toiletsNoResults": "Tiada tandas awam yang dipetakan ditemui di kawasan ini. Ini tidak semestinya bermakna tiada tandas awam di kawasan tersebut.",
  "toiletsNoPublic": "Tiada tandas awam yang disahkan sepadan dengan penapis ini.",
  "toiletsIncreaseRadius": "Besarkan jejari",
  "toiletsSearchAnotherCity": "Cari bandar lain",
  "toiletsRestricted": "Akses terhad",
  "toiletsAccessUnknown": "Akses belum disahkan",
  "toiletsStandalone": "Tandas awam berasingan",
  "toiletsSort": "Susun",
  "toiletsNearest": "Paling dekat dahulu",
  "toiletsSortAccess": "Akses awam dahulu",
  "toiletsSortFree": "Percuma dahulu",
  "toiletsSortAccessible": "Boleh diakses dahulu",
  "toiletsLegend": "Petunjuk penanda",
  "halalCertificationListed": "Pensijilan disenaraikan",
  "taxiOffice": "Pejabat atau pusat penghantaran teksi",
  "taxiPhoneAvailable": "Nombor telefon tersedia",
  "taxiWheelchairInfo": "Maklumat akses kerusi roda tersedia",
  "taxiSortContact": "Maklumat hubungan tersedia dahulu",
  "taxiLit": "Pencahayaan",
  "weatherPacking": "Cadangan umum berdasarkan cuaca",
  "weatherKmh": "km/j",
  "weatherMs": "m/s",
  "weatherLastUpdated": "Kemas kini terakhir",
  "weatherIndicatorSnow": "Salji mungkin berlaku",
  "attractionsListView": "Senarai berdekatan",
  "attractionsViewpoint": "Tempat tinjau",
  "attractionsNatural": "Tarikan alam semula jadi",
  "attractionsSaved": "Disimpan",
  "toiletsListView": "Senarai berdekatan",
  "toiletsCustomersOnly": "Untuk pelanggan atau pelawat sahaja",
  "toiletsChanging": "Meja menukar lampin bayi",
  "toiletsHandwashing": "Kemudahan mencuci tangan",
  "toiletsVenue": "Tandas di dalam tempat awam",
  "cardsAccepted": "Kad biasanya diterima",
  "denominations": "Pecahan biasa",
  "publicTransportLegend": "Petunjuk penanda",
  "taxiLegend": "Petunjuk penanda"
};
