import { labels } from './i18n.js';

Object.assign(labels.tr, {
  carRentalTitle: 'Araç Kiralama',
  carRentalSubtitle: 'Harita verilerinde mevcutsa resmi iletişim bağlantılarıyla birlikte haritalanmış araç kiralama ofislerini bulun.',
  carRentalOpen: 'Araç Kiralama',
  carRentalBack: 'Planlayıcıya dön',
  carRentalNotice: 'Araç kiralama bilgileri kullanıcıların katkıda bulunduğu harita verilerine dayanır ve eksik ya da güncel olmayabilir. Ofis konumunu, çalışma saatlerini, uygunluk şartlarını, fiyatı, sigortayı, depozitoyu ve araç müsaitliğini doğrudan kiralama şirketiyle doğrulayın.',
  carRentalAvailabilityNotice: 'Bir ofisin sonuçlarda görünmesi, araçların şu anda müsait olduğu anlamına gelmez.',
  carRentalLiveNotice: 'Bu harita araması canlı fiyatları veya araç müsaitliğini göstermez. Müsaitliği ve son fiyatı doğrulamak için kiralama ofisiyle iletişime geçin veya resmi web sitesini kullanın.',
  carRentalUseLocation: 'Konumumu kullan',
  carRentalManualSearch: 'Şehir, havalimanı veya istasyon ara',
  carRentalManualPlaceholder: 'Şehir, havalimanı, tren istasyonu...',
  carRentalSearchNear: 'Yakınında ara',
  carRentalDestinationSearch: 'Varış noktası',
  carRentalAirportSearch: 'Havalimanı',
  carRentalStationSearch: 'Tren veya otobüs istasyonu',
  carRentalSearch: 'Ara',
  carRentalSearchThisArea: 'Bu alanda ara',
  carRentalRecentre: 'Konumuma dön',
  carRentalFitResults: 'Tüm sonuçları göster',
  carRentalRadius: 'Yarıçap',
  carRentalRequestingLocation: 'Konum isteniyor...',
  carRentalSearching: 'Haritadaki araç kiralama ofisleri aranıyor...',
  carRentalLocationDenied: 'Konum izni reddedildi. Bunun yerine varış noktası arayın.',
  carRentalLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  carRentalServiceUnavailable: 'Harita veri hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  carRentalTimedOut: 'Arama zaman aşımına uğradı. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  carRentalTooMany: 'Çok fazla sonuç bulundu. Daha küçük bir yarıçap seçin.',
  carRentalOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  carRentalCached: 'Önbelleğe alınmış araç kiralama sonuçları gösteriliyor.',
  carRentalNoResults: 'Bu alanda haritaya eklenmiş araç kiralama ofisi bulunamadı. Bu, bölgede hiç ofis olmadığı anlamına gelmez.',
  carRentalRetry: 'Tekrar dene',
  carRentalIncreaseRadius: 'Yarıçapı artır',
  carRentalSearchAnother: 'Başka bir varış noktası ara',
  carRentalMapView: 'Harita',
  carRentalListView: 'Yakındakiler',
  carRentalAllOffices: 'Tüm ofisler',
  carRentalAirportOffice: 'Havalimanı araç kiralama ofisi',
  carRentalCityOffice: 'Şehir araç kiralama ofisi',
  carRentalRailwayOffice: 'Tren istasyonu araç kiralama ofisi',
  carRentalBusOffice: 'Otobüs terminali araç kiralama ofisi',
  carRentalHotelDesk: 'Otel veya tesis kiralama masası',
  carRentalIndependentOffice: 'Bağımsız yerel kiralama ofisi',
  carRentalUnknownOffice: 'Konum türü bilinmiyor',
  carRentalAtAirport: 'Havalimanında veya yakınında',
  carRentalWebsiteAvailable: 'Resmi web sitesi mevcut',
  carRentalPhoneAvailable: 'Telefon numarası mevcut',
  carRentalSort: 'Sırala',
  carRentalSortAirport: 'Önce havalimanı ofisleri',
  carRentalSortWebsite: 'Resmi web sitesi olanlar',
  carRentalLegend: 'Harita işaretleri',
  carRentalBrand: 'Marka',
  carRentalOperator: 'İşletmeci',
  carRentalLocationType: 'Konum türü',
  carRentalLocationContext: 'Havalimanı veya istasyon',
  carRentalEmail: 'E-posta',
  carRentalBookingWebsite: 'Resmi rezervasyon sitesi',
  carRentalBranchRef: 'Şube kodu',
  carRentalOfficialWebsiteListed: 'Harita verilerinde resmi web sitesi listeleniyor',
  carRentalOfficialBookingListed: 'Harita verilerinde resmi rezervasyon sitesi listeleniyor',
  carRentalOpenOfficialWebsite: 'Resmi web sitesini aç',
  carRentalCallOffice: 'Ofisi telefonla ara',
  carRentalChecklistTitle: 'Rezervasyondan önce doğrudan doğrulayın',
  carRentalChecklistIntro: 'Bu harita araması ülkeye özgü hukuki tavsiye sağlamaz.',
  carRentalCheckAge: 'Sürücü için yaş şartı',
  carRentalCheckLicence: 'Geçerli sürücü belgesi şartları',
  carRentalCheckPermit: 'Uluslararası Sürüş İzni şartları',
  carRentalCheckDeposit: 'Depozito ve ödeme kartı şartları',
  carRentalCheckInsurance: 'Sigorta kapsamı ve istisnalar',
  carRentalCheckFuel: 'Yakıt politikası',
  carRentalCheckMileage: 'Kilometre sınırları',
  carRentalCheckDriver: 'Ek sürücü ücretleri',
  carRentalCheckBorder: 'Sınır ötesi kullanım kısıtlamaları',
  carRentalCheckCancel: 'İptal politikası',
  carRentalCheckTimes: 'Teslim alma ve iade saatleri',
  carRentalCheckLate: 'Geç iade ücretleri',
});
