import { labels } from './i18n.js';

Object.assign(labels.tr, {
  publicTransportTitle: 'Toplu Taşıma',
  publicTransportSubtitle: 'Yakınınızdaki tren, metro, tramvay, otobüs ve feribot duraklarını yol tarifleri ve mevcut seyahat bilgileriyle bulun.',
  publicTransportOpen: 'Toplu Taşıma',
  publicTransportBack: 'Planlayıcıya dön',
  publicTransportNotice: 'Toplu taşıma bilgileri kullanıcıların katkıda bulunduğu açık harita verilerinden alınır ve eksik ya da güncel olmayabilir. Güzergâhları, çalışma saatlerini, ücretleri ve erişilebilirliği resmi ulaşım işletmecisiyle doğrulayın.',
  publicTransportLiveNotice: 'Canlı kalkış saatleri ve yolculuk planlama şu anda sunulmamaktadır.',
  publicTransportUseLocation: 'Konumumu kullan',
  publicTransportUseDestination: 'Seyahat varış noktasını kullan',
  publicTransportManualSearch: 'Başka bir şehir ara',
  publicTransportManualPlaceholder: 'Şehir veya varış noktası...',
  publicTransportSearch: 'Ara',
  publicTransportSearchThisArea: 'Bu alanda ara',
  publicTransportRecentre: 'Haritayı yeniden merkezle',
  publicTransportFitResults: 'Tüm sonuçları göster',
  publicTransportRadius: 'Yarıçap',
  publicTransportRequestingLocation: 'Konum isteniyor...',
  publicTransportSearching: 'Haritadaki toplu taşıma noktaları aranıyor...',
  publicTransportLocationDenied: 'Konum izni reddedildi. Bunun yerine varış noktası arayın.',
  publicTransportLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  publicTransportServiceUnavailable: 'Harita veri hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  publicTransportTimedOut: 'Arama zaman aşımına uğradı. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  publicTransportTooMany: 'Çok fazla sonuç bulundu. Daha küçük bir yarıçap seçin.',
  publicTransportOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  publicTransportCached: 'Önbelleğe alınmış toplu taşıma sonuçları gösteriliyor.',
  publicTransportNoResults: 'Bu alanda haritaya eklenmiş toplu taşıma durağı veya istasyonu bulunamadı. Bu, bölgede hiç olmadığı anlamına gelmez.',
  publicTransportRetry: 'Tekrar dene',
  publicTransportIncreaseRadius: 'Yarıçapı artır',
  publicTransportSearchAnother: 'Başka bir şehir ara',
  publicTransportMapView: 'Harita',
  publicTransportListView: 'Yakındakiler',
  publicTransportAll: 'Tüm toplu taşıma',
  publicTransportSort: 'Sırala',
  publicTransportLegend: 'Harita işaretleri',
  transportTrain: 'Tren istasyonu',
  transportMetro: 'Metro istasyonu',
  transportLightRail: 'Hafif raylı sistem istasyonu',
  transportTram: 'Tramvay durağı',
  transportBusStation: 'Otobüs terminali',
  transportBusStop: 'Otobüs durağı',
  transportFerry: 'Feribot terminali',
  transportOther: 'Diğer toplu taşıma noktası',
  transportType: 'Ulaşım türü',
  transportOperator: 'İşletmeci',
  transportNetwork: 'Ulaşım ağı',
  transportReference: 'Referans',
  transportLines: 'Hatlar veya güzergâhlar',
  transportShelter: 'Kapalı bekleme alanı',
  transportSeating: 'Oturma yeri',
  transportToilets: 'Tuvaletler',
  transportToiletsAvailable: 'Tuvalet mevcut',
  transportShelterAvailable: 'Kapalı bekleme alanı mevcut',
  transportOfficialWebsite: 'Resmi web sitesi',
  transportSortType: 'Ulaşım türü',

  taxiTitle: 'Taksi Hizmetleri',
  taxiSubtitle: 'Konumunuzun veya varış noktanızın yakınındaki haritaya eklenmiş taksi duraklarını ve açıkça tanımlanmış taksi ofislerini bulun.',
  taxiOpen: 'Taksi Hizmetleri',
  taxiBack: 'Planlayıcıya dön',
  taxiNotice: 'Taksi bilgileri kullanıcıların katkıda bulunduğu açık harita verilerinden alınır ve eksik ya da güncel olmayabilir. Bir taksi noktasının gösterilmesi; ruhsat, güvenlik, fiyat veya mevcut araç garantisi değildir. Ücretleri, çalışma saatlerini, ödeme yöntemlerini ve resmi iletişim bilgilerini yerel olarak doğrulayın.',
  taxiLiveNotice: 'Bu uygulama şu anda taksi rezervasyonu yapmaz veya gerçek zamanlı araç bilgisi sağlamaz.',
  taxiUseLocation: 'Konumumu kullan',
  taxiUseDestination: 'Seyahat varış noktasını kullan',
  taxiManualSearch: 'Başka bir şehir ara',
  taxiManualPlaceholder: 'Şehir veya varış noktası...',
  taxiSearch: 'Ara',
  taxiSearchThisArea: 'Bu alanda ara',
  taxiRecentre: 'Haritayı yeniden merkezle',
  taxiFitResults: 'Tüm sonuçları göster',
  taxiRadius: 'Yarıçap',
  taxiRequestingLocation: 'Konum isteniyor...',
  taxiSearching: 'Haritadaki taksi hizmetleri aranıyor...',
  taxiLocationDenied: 'Konum izni reddedildi. Bunun yerine varış noktası arayın.',
  taxiLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  taxiServiceUnavailable: 'Harita veri hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  taxiTimedOut: 'Arama zaman aşımına uğradı. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  taxiTooMany: 'Çok fazla sonuç bulundu. Daha küçük bir yarıçap seçin.',
  taxiOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  taxiCached: 'Önbelleğe alınmış taksi sonuçları gösteriliyor.',
  taxiNoResults: 'Bu alanda haritaya eklenmiş taksi durağı veya açıkça tanımlanmış taksi ofisi bulunamadı. Bu, bölgede hiç olmadığı anlamına gelmez.',
  taxiRetry: 'Tekrar dene',
  taxiIncreaseRadius: 'Yarıçapı artır',
  taxiSearchAnother: 'Başka bir şehir ara',
  taxiMapView: 'Harita',
  taxiListView: 'Yakındakiler',
  taxiAll: 'Tüm taksi hizmetleri',
  taxiRank: 'Taksi durağı',
  taxiAirportRank: 'Havalimanı taksi durağı',
  taxiStationRank: 'Tren veya metro istasyonu taksi durağı',
  taxiBusRank: 'Otobüs terminali taksi durağı',
  taxiOffice: 'Taksi ofisi veya çağrı merkezi',
  taxiMotorcycle: 'Motosiklet taksi durağı',
  taxiWater: 'Deniz taksisi durağı',
  taxiOther: 'Diğer haritalanmış taksi hizmeti',
  taxiPhoneAvailable: 'Telefon numarası mevcut',
  taxiWheelchairInfo: 'Tekerlekli sandalye erişimi bilgisi mevcut',
  taxiSort: 'Sırala',
  taxiSortType: 'Taksi hizmeti türü',
  taxiSortContact: 'İletişim bilgisi mevcut',
  taxiLegend: 'Harita işaretleri',
  taxiType: 'Taksi hizmeti türü',
  taxiCapacity: 'Kapasite',
  taxiVehicle: 'Araç türü',
  taxiLit: 'Aydınlatma',
  taxiFee: 'Ücret bilgisi',
  taxiCall: 'Taksi hizmetini telefonla ara',

  attractionsTitle: 'Gezilecek Yerler',
  attractionsSubtitle: 'Haritaya eklenmiş ziyaret noktalarını, yeniden kullanılabilir lisanslı fotoğrafları ve kısa İngilizce kaynak özetleriyle bulun.',
  attractionsOpen: 'Gezilecek Yerler',
  attractionsBack: 'Planlayıcıya dön',
  attractionsNotice: 'Gezilecek yer bilgileri, fotoğraflar ve tarihçe özetleri kullanıcıların katkıda bulunduğu açık veri kaynaklarından alınır ve eksik ya da güncel olmayabilir. Seyahatten önce çalışma saatlerini, erişimi, giriş ücretlerini ve ziyaretçi kısıtlamalarını doğrulayın.',
  attractionsPhotoNotice: 'Fotoğraflar yalnızca güvenilir bir eşleşme ve yeniden kullanıma uygun lisans bulunduğunda gösterilir.',
  attractionsUseLocation: 'Konumumu kullan',
  attractionsUseDestination: 'Seyahat varış noktasını kullan',
  attractionsManualSearch: 'Başka bir şehir ara',
  attractionsSearch: 'Ara',
  attractionsSearchAnother: 'Başka bir varış noktası ara',
  attractionsRequestingLocation: 'Konum isteniyor...',
  attractionsLocationDenied: 'Konum izni reddedildi. Bunun yerine şehir arayın.',
  attractionsLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  attractionsSearching: 'Haritadaki gezilecek yerler aranıyor...',
  attractionsLoadingPhotos: 'Fotoğraflar yükleniyor...',
  attractionsLoadingHistory: 'Tarihçe bilgileri yükleniyor...',
  attractionsServiceUnavailable: 'Gezilecek yer hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  attractionsWikipediaUnavailable: 'Wikipedia hizmeti kullanılamıyor.',
  attractionsImageUnavailable: 'Görsel hizmeti kullanılamıyor.',
  attractionsTimedOut: 'Gezilecek yer araması çok uzun sürdü. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  attractionsOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  attractionsCached: 'Önbelleğe alınmış gezilecek yer sonuçları gösteriliyor.',
  attractionsNoResults: 'Bu alanda haritaya eklenmiş gezilecek yer bulunamadı. Bu, bölgede hiç olmadığı anlamına gelmez.',
  attractionsNoLicensedImage: 'Lisanslı fotoğraf mevcut değil',
  attractionsNoHistory: 'İngilizce tarihçe bilgisi mevcut değil',
  attractionsPhotoView: 'Fotoğraf kartları',
  attractionsListView: 'Yakındakiler',
  attractionsMapView: 'Harita',
  attractionsAll: 'Tüm gezilecek yerler',
  attractionsHistoric: 'Tarihi alan',
  attractionsMuseum: 'Müze',
  attractionsGallery: 'Sanat galerisi',
  attractionsMonument: 'Anıt veya anma yapısı',
  attractionsArchaeological: 'Arkeolojik alan',
  attractionsCastle: 'Kale, hisar veya saray',
  attractionsReligious: 'Dini miras alanı',
  attractionsViewpoint: 'Seyir noktası',
  attractionsNatural: 'Doğal güzellik',
  attractionsPark: 'Park veya bahçe',
  attractionsZoo: 'Hayvanat bahçesi veya akvaryum',
  attractionsTheme: 'Tema parkı',
  attractionsArtwork: 'Kamusal sanat eseri',
  attractionsCultural: 'Kültürel gezilecek yer',
  attractionsOther: 'Diğer haritalanmış gezilecek yer',
  attractionsPhotoAvailable: 'Fotoğraf mevcut',
  attractionsHistoryAvailable: 'İngilizce tarihçe mevcut',
  attractionsSortCategory: 'Kategori',
  attractionsSortPhoto: 'Önce fotoğrafı olanlar',
  attractionsSortHistory: 'Önce tarihçe bilgisi olanlar',
  attractionsSortComplete: 'En kapsamlı bilgi',
  attractionsCategory: 'Kategori',
  attractionsAdmission: 'Giriş ücreti',
  attractionsInfoSource: 'Bilgi kaynağı',
  attractionsDetails: 'Ayrıntılar',
  attractionsClose: 'Ayrıntıları kapat',
  attractionsSave: 'Favorilere kaydet',
  attractionsSaved: 'Kaydedildi',
  attractionsReadMore: 'Wikipedia’da devamını oku',

  toiletsTitle: 'Umumi Tuvaletler',
  toiletsSubtitle: 'Yakınınızda veya bir varış noktasında haritaya eklenmiş umumi tuvaletleri ve açıkça etiketlenmiş mekân tuvaletlerini bulun.',
  toiletsOpen: 'Umumi Tuvaletler',
  toiletsBack: 'Planlayıcıya dön',
  toiletsNotice: 'Tuvalet bilgileri kullanıcıların katkıda bulunduğu harita verilerine dayanır ve eksik ya da güncel olmayabilir. Mümkün olduğunda erişimi, çalışma saatlerini, ücretleri ve erişilebilirliği doğrulayın.',
  toiletsAccessNotice: 'Erişim bilgisinin bilinmemesi, tuvaletin halka açık olduğu anlamına gelmez. İşletme veya mekân içindeki tuvaletler alışveriş, bilet, anahtar ya da izin gerektirebilir.',
  toiletsUseLocation: 'Konumumu kullan',
  toiletsManualSearch: 'Şehir veya varış noktası ara',
  toiletsManualPlaceholder: 'Şehir, istasyon, park...',
  toiletsSearch: 'Ara',
  toiletsSearchThisArea: 'Bu alanda ara',
  toiletsRecentre: 'Konumuma dön',
  toiletsFitResults: 'Tüm sonuçları göster',
  toiletsRadius: 'Yarıçap',
  toiletsRequestingLocation: 'Konum isteniyor...',
  toiletsSearching: 'Haritadaki tuvaletler aranıyor...',
  toiletsLocationDenied: 'Konum izni reddedildi. Bunun yerine şehir veya varış noktası arayın.',
  toiletsLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  toiletsServiceUnavailable: 'Harita veri hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  toiletsTimedOut: 'Arama zaman aşımına uğradı. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  toiletsTooMany: 'Çok fazla sonuç bulundu. Daha küçük bir yarıçap seçin.',
  toiletsOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  toiletsCached: 'Önbelleğe alınmış tuvalet sonuçları gösteriliyor.',
  toiletsNoResults: 'Bu alanda haritaya eklenmiş umumi tuvalet bulunamadı. Bu, bölgede hiç olmadığı anlamına gelmez.',
  toiletsNoPublic: 'Bu filtrelerle eşleşen, halka açık olduğu doğrulanmış tuvalet bulunamadı.',
  toiletsRetry: 'Tekrar dene',
  toiletsIncreaseRadius: 'Yarıçapı artır',
  toiletsSearchAnotherCity: 'Başka bir şehir ara',
  toiletsMapView: 'Harita',
  toiletsListView: 'Yakındakiler',
  toiletsAllResults: 'Tüm sonuçlar',
  toiletsPublicAccess: 'Halka açık',
  toiletsCustomersOnly: 'Yalnızca müşteriler veya ziyaretçiler',
  toiletsRestricted: 'Kısıtlı erişim',
  toiletsAccessUnknown: 'Erişim doğrulanmadı',
  toiletsFree: 'Ücretsiz',
  toiletsPaid: 'Ücretli',
  toiletsFeeUnknown: 'Ücret bilgisi bilinmiyor',
  toiletsOpenNow: 'Şimdi açık',
  toiletsOpen24: '24 saat açık',
  toiletsWheelchair: 'Tekerlekli sandalye erişimine uygun',
  toiletsWheelchairLimited: 'Sınırlı tekerlekli sandalye erişimi',
  toiletsWheelchairNo: 'Tekerlekli sandalye erişimine uygun değil',
  toiletsWheelchairUnknown: 'Erişilebilirlik bilinmiyor',
  toiletsChanging: 'Bebek bakım masası',
  toiletsFemale: 'Kadın',
  toiletsMale: 'Erkek',
  toiletsUnisex: 'Unisex',
  toiletsHandwashing: 'El yıkama alanı',
  toiletsSoap: 'Sabun',
  toiletsPaper: 'Tuvalet kâğıdı',
  toiletsHotWater: 'Sıcak su',
  toiletsShower: 'Duş',
  toiletsDrinkingWater: 'İçme suyu',
  toiletsSeated: 'Klozet',
  toiletsSquat: 'Alaturka tuvalet',
  toiletsUrinal: 'Pisuvar',
  toiletsOperator: 'İşletmeci',
  toiletsSupervised: 'Görevli mevcut',
  toiletsInside: 'İçeride',
  toiletsStandalone: 'Bağımsız umumi tuvalet',
  toiletsVenue: 'Halka açık bir mekânın içindeki tuvalet',
  toiletsPortable: 'Seyyar tuvalet',
  toiletsSort: 'Sırala',
  toiletsNearest: 'En yakın önce',
  toiletsSortName: 'Ad',
  toiletsSortAccess: 'Önce halka açık olanlar',
  toiletsSortFree: 'Önce ücretsiz olanlar',
  toiletsSortOpen: 'Şimdi açık',
  toiletsSortAccessible: 'Önce erişilebilir olanlar',
  toiletsLegend: 'Harita işaretleri',
});
