import { labels } from './i18n.js';
import './turkish-car-rental-copy.js';
import './turkish-travel-tools-copy.js';
import './weather-layout-bootstrap.js';
import './money-currency-picker-bootstrap.js';

Object.assign(labels.tr, {
  halalRestaurantsTitle: 'Helal Restoranlar',
  halalRestaurantsSubtitle: 'Yakınınızda veya varış noktanızda, harita verilerinde açıkça helal olarak etiketlenmiş restoranları bulun.',
  halalRestaurantsOpen: 'Helal Restoranlar',
  halalRestaurantsBack: 'Planlayıcıya dön',
  halalNotice: 'Restoran bilgileri kullanıcıların katkıda bulunduğu harita verilerine dayanır ve eksik ya da güncel olmayabilir. Seyahat etmeden veya sipariş vermeden önce helal durumunu, sertifikayı, çalışma saatlerini ve menü ayrıntılarını doğrudan restoranla doğrulayın.',
  halalMeaningNotice: '“Tamamen Helal”, harita verilerinde tüm yiyeceklerin helal olarak belirtildiği anlamına gelir. “Helal Seçenekleri”, yalnızca bazı ürünlerin helal olabileceği anlamına gelir.',
  halalUseLocation: 'Konumumu kullan',
  halalManualSearch: 'Şehir veya varış noktası ara',
  halalManualPlaceholder: 'Şehir, mahalle, havalimanı...',
  halalSearch: 'Ara',
  halalSearchThisArea: 'Bu alanda ara',
  halalRecentre: 'Konumuma dön',
  halalFitResults: 'Tüm sonuçları haritada göster',
  halalRadius: 'Yarıçap',
  halalRequestingLocation: 'Konum isteniyor...',
  halalSearching: 'Haritadaki helal restoranlar aranıyor...',
  halalLocationDenied: 'Konum izni reddedildi. Bunun yerine şehir veya varış noktası arayın.',
  halalLocationUnavailable: 'Konum bu cihazda veya tarayıcıda kullanılamıyor.',
  halalServiceUnavailable: 'Harita veri hizmeti kullanılamıyor. Lütfen birazdan tekrar deneyin.',
  halalTimedOut: 'Arama zaman aşımına uğradı. Daha küçük bir yarıçap seçin veya tekrar deneyin.',
  halalTooMany: 'Çok fazla sonuç bulundu. Daha küçük bir yarıçap seçin.',
  halalNoResults: 'Bu alanda haritaya eklenmiş helal restoran bulunamadı. Bu, bölgede hiç helal restoran olmadığı anlamına gelmez.',
  halalNoReliable: 'Bu filtrelerle eşleşen güvenilir helal etiketli sonuç bulunamadı.',
  halalCached: 'Önbelleğe alınmış restoran sonuçları gösteriliyor.',
  halalOffline: 'Çevrimdışı görünüyorsunuz. Varsa önbelleğe alınmış sonuçlar gösteriliyor.',
  halalRetry: 'Tekrar dene',
  halalIncreaseRadius: 'Yarıçapı artır',
  halalSearchAnotherCity: 'Başka bir şehir ara',
  halalMapView: 'Harita',
  halalListView: 'Yakındakiler',
  halalAllReliable: 'Tüm güvenilir sonuçlar',
  halalOnly: 'Tamamen Helal',
  halalOptions: 'Helal Seçenekleri',
  halalCertificationListed: 'Sertifika Bilgisi Mevcut',
  halalLegacy: 'Eski Helal Etiketi',
  halalPossible: 'Olası / Doğrulanmamış',
  halalRestaurant: 'Restoran',
  halalFastFood: 'Hızlı yemek',
  halalCafe: 'Kafe',
  halalFoodCourt: 'Yeme-içme alanı',
  halalOpenNow: 'Şimdi açık',
  halalTakeaway: 'Paket servis',
  halalDelivery: 'Teslimat',
  halalWheelchair: 'Tekerlekli sandalye erişimine uygun',
  halalCuisine: 'Mutfak',
  halalAllCuisines: 'Tüm mutfaklar',
  halalSort: 'Sırala',
  halalNearest: 'En yakın önce',
  halalSortName: 'Ad',
  halalSortStatus: 'Helal durumu',
  halalSortOpen: 'Şimdi açık',
  halalSortCuisine: 'Mutfak',
  halalCertificationNotice: 'Kaynak verilerde sertifika bilgisi listeleniyor.',
  halalLegacyNotice: 'Doğrulanmamış eski helal etiketi.',
  halalPossibleNotice: 'Kaynak verilerde olası bir helal ifadesi bulunuyor; doğrudan restoranla doğrulayın.',
  halalOpeningUnavailable: 'Açık veya kapalı bilgisi mevcut değil',
  halalOpen: 'Şimdi açık',
  halalClosed: 'Şimdi kapalı',
  halalCuisineLabel: 'Mutfak',
  halalMenu: 'Menü',
  halalPrice: 'Fiyat düzeyi',
  halalOutdoor: 'Açık hava oturma alanı',
  halalInfoIssue: 'Bilgiler yanlış veya eksik mi?',
  halalCopyDetails: 'Ayrıntıları kopyala',
  halalCopiedDetails: 'Ayrıntılar kopyalandı.',
  halalLegend: 'Harita işaretleri',
  osmAttribution: 'Veri © OpenStreetMap katkıda bulunanlar',
});
