export const urduExtraLabelsC: Record<string, string> = {
  toiletsTitle: "عوامی بیت الخلا",
  toiletsSubtitle: "اپنے قریب یا منزل کے نزدیک نقشے پر موجود عوامی بیت الخلا اور عوامی مقامات کے واضح طور پر درج بیت الخلا تلاش کریں۔",
  toiletsOpen: "عوامی بیت الخلا",
  toiletsBack: "منصوبہ ساز پر واپس جائیں",
  toiletsNotice: "بیت الخلا کی معلومات صارفین کے فراہم کردہ نقشہ ڈیٹا سے آتی ہیں اور نامکمل یا پرانی ہو سکتی ہیں۔ جہاں ممکن ہو رسائی، اوقات، فیس اور سہولتوں کی تصدیق کریں۔",
  toiletsAccessNotice: "نامعلوم رسائی کا مطلب عوامی رسائی نہیں۔ دکانوں یا عوامی مقامات کے اندر بیت الخلا کے لیے خریداری، ٹکٹ، چابی یا اجازت درکار ہو سکتی ہے۔",
  toiletsUseLocation: "میرا مقام استعمال کریں",
  toiletsManualSearch: "شہر یا منزل تلاش کریں",
  toiletsManualPlaceholder: "شہر، اسٹیشن، پارک...",
  toiletsSearch: "تلاش کریں",
  toiletsSearchThisArea: "اس علاقے میں تلاش کریں",
  toiletsRecentre: "میرے مقام پر دوبارہ مرکز کریں",
  toiletsFitResults: "تمام نتائج دکھائیں",
  toiletsRadius: "دائرہ",
  toiletsRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  toiletsSearching: "نقشے پر بیت الخلا تلاش ہو رہے ہیں...",
  toiletsLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے شہر یا منزل تلاش کریں۔",
  toiletsLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  toiletsServiceUnavailable: "نقشہ ڈیٹا سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  toiletsTimedOut: "تلاش کا وقت ختم ہو گیا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  toiletsTooMany: "نتائج بہت زیادہ ہیں۔ چھوٹا دائرہ آزمائیں۔",
  toiletsOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  toiletsCached: "محفوظ بیت الخلا نتائج دکھائے جا رہے ہیں۔",
  toiletsNoResults: "اس علاقے میں کوئی نقشہ شدہ عوامی بیت الخلا نہیں ملا۔ اس کا مطلب یہ نہیں کہ یہاں کوئی موجود نہیں۔",
  toiletsNoPublic: "ان فلٹرز سے تصدیق شدہ عوامی بیت الخلا نہیں ملا۔",
  toiletsRetry: "دوبارہ کوشش کریں",
  toiletsIncreaseRadius: "دائرہ بڑھائیں",
  toiletsSearchAnotherCity: "دوسرا شہر تلاش کریں",
  toiletsMapView: "نقشہ",
  toiletsListView: "قریبی فہرست",
  toiletsAllResults: "تمام نتائج",
  toiletsPublicAccess: "عوامی رسائی",
  toiletsCustomersOnly: "صرف گاہک یا زائرین",
  toiletsRestricted: "محدود رسائی",
  toiletsAccessUnknown: "رسائی کی تصدیق نہیں",
  toiletsFree: "مفت",
  toiletsPaid: "فیس والا",
  toiletsFeeUnknown: "فیس نامعلوم",
  toiletsOpenNow: "ابھی کھلا ہے",
  toiletsOpen24: "24 گھنٹے کھلا",
  toiletsWheelchair: "وہیل چیئر کے لیے قابلِ رسائی",
  toiletsWheelchairLimited: "وہیل چیئر کی محدود رسائی",
  toiletsWheelchairNo: "وہیل چیئر کے لیے قابلِ رسائی نہیں",
  toiletsWheelchairUnknown: "وہیل چیئر رسائی نامعلوم",
  toiletsChanging: "بچے کا ڈائپر بدلنے کی جگہ",
  toiletsFemale: "خواتین",
  toiletsMale: "مرد",
  toiletsUnisex: "مشترکہ",
  toiletsHandwashing: "ہاتھ دھونے کی سہولت",
  toiletsSoap: "صابن",
  toiletsPaper: "ٹشو پیپر",
  toiletsHotWater: "گرم پانی",
  toiletsShower: "شاور",
  toiletsDrinkingWater: "پینے کا پانی",
  toiletsSeated: "بیٹھنے والا بیت الخلا",
  toiletsSquat: "فرشی بیت الخلا",
  toiletsUrinal: "پیشاب خانہ",
  toiletsOperator: "منتظم",
  toiletsSupervised: "نگرانی والا",
  toiletsInside: "اندر",
  toiletsStandalone: "الگ عوامی بیت الخلا",
  toiletsVenue: "عوامی مقام کے اندر بیت الخلا",
  toiletsPortable: "موبائل بیت الخلا",
  toiletsSort: "ترتیب دیں",
  toiletsNearest: "قریب ترین",
  toiletsSortName: "نام",
  toiletsSortAccess: "عوامی رسائی پہلے",
  toiletsSortFree: "مفت پہلے",
  toiletsSortOpen: "ابھی کھلے ہوئے پہلے",
  toiletsSortAccessible: "قابلِ رسائی پہلے",
  toiletsLegend: "نقشہ نشانات کی وضاحت",
};
