export const urduExtraLabelsA: Record<string, string> = {
  osmAttribution: "ڈیٹا © OpenStreetMap شراکت دار",
  attractionsSubtitle: "لائسنس یافتہ تصاویر اور انگریزی ذرائع سے مختصر تعارف کے ساتھ نقشے پر موجود سیاحتی مقامات تلاش کریں۔",
  attractionsNotice: "معلومات، تصاویر اور تاریخی خلاصے کھلے اور صارفین کے فراہم کردہ ڈیٹا سے آتے ہیں اور نامکمل یا پرانے ہو سکتے ہیں۔ سفر سے پہلے اوقات، رسائی، داخلہ فیس اور پابندیوں کی تصدیق کریں۔",
  attractionsPhotoNotice: "تصاویر صرف اس وقت دکھائی جاتی ہیں جب قابلِ اعتماد مطابقت اور دوبارہ استعمال کی اجازت والا لائسنس دستیاب ہو۔",
  attractionsLocationDenied: "مقام کی اجازت مسترد کر دی گئی۔ اس کے بجائے شہر تلاش کریں۔",
  attractionsLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  attractionsLoadingPhotos: "تصاویر لوڈ ہو رہی ہیں...",
  attractionsLoadingHistory: "تاریخی معلومات لوڈ ہو رہی ہیں...",
  attractionsServiceUnavailable: "سیاحتی مقامات کی سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  attractionsWikipediaUnavailable: "ویکیپیڈیا سروس دستیاب نہیں۔",
  attractionsImageUnavailable: "تصاویر کی سروس دستیاب نہیں۔",
  attractionsNoLicensedImage: "کوئی لائسنس یافتہ تصویر دستیاب نہیں",
  attractionsNoHistory: "انگریزی میں کوئی تاریخی خلاصہ دستیاب نہیں",
  attractionsPhotoView: "تصاویر والے کارڈز",
  attractionsArchaeological: "آثارِ قدیمہ کا مقام",
  attractionsCastle: "قلعہ، محل یا فورٹ",
  attractionsZoo: "چڑیا گھر یا ایکویریم",
  attractionsTheme: "تھیم پارک",
  attractionsArtwork: "عوامی فن پارہ",
  attractionsCultural: "ثقافتی مقام",
  attractionsOther: "دوسرا نقشہ شدہ مقام",
  attractionsPhotoAvailable: "تصویر دستیاب ہے",
  attractionsHistoryAvailable: "انگریزی تاریخی خلاصہ دستیاب ہے",
  attractionsSortCategory: "زمرہ",
  attractionsSortPhoto: "تصاویر والے مقامات پہلے",
  attractionsSortHistory: "تاریخی خلاصے والے مقامات پہلے",
  attractionsSortComplete: "سب سے مکمل معلومات",
  attractionsInfoSource: "معلومات کا ماخذ",
  attractionsSave: "پسندیدہ میں شامل کریں",
  attractionsSaved: "محفوظ ہو گیا",
};
