export const urduFlightLabels: Record<string, string> = {
  flightModeTitle: "پرواز میں نماز اور قبلہ",
  flightModeSubtitle: "پرواز کے دوران نماز کے اوقات اور حقیقی سمت کے مطابق قبلہ کے اندازوں کے لیے آف لائن فضائی راستہ تیار کریں۔",
  flightModeOpen: "فلائٹ موڈ کھولیں",
  flightModeBack: "منصوبہ ساز پر واپس جائیں",
  flightPrepareStage: "پرواز کو آف لائن تیار کریں",
  flightDashboardStage: "پرواز کے دوران ڈیش بورڈ",
  flightBestEstimate: "براہِ راست GPS یا محفوظ شدہ فضائی راستے کی بنیاد پر بہترین دستیاب اندازہ۔",
  flightOfflineNotice: "تیار کیے گئے پروازی حسابات آف لائن دستیاب ہیں۔ براہِ راست GPS کی دستیابی آلے، جہاز، نشست اور حفاظتی پابندیوں پر منحصر ہے۔",
  flightSafetyNotice: "جہاں ضروری ہو اپنے آلے کو فلائٹ موڈ میں رکھیں اور عملے کی تمام ہدایات پر عمل کریں۔",
  flightRouteDisclaimer: "ہوائی اڈے سے ہوائی اڈے تک عظیم دائرے کا سیدھا راستہ ایک اندازہ ہے اور فضائی کمپنی کے اصل راستے سے مختلف ہو سکتا ہے۔",
  flightAltitudeDisclaimer: "کروزنگ بلندی پر نظر آنے والا افق اور مشاہدہ شدہ طلوع یا غروبِ آفتاب زمینی حسابات سے مختلف ہو سکتا ہے۔ اپنی معتبر دینی رہنمائی پر عمل کریں۔",
  flightDepartureAirport: "روانگی کا ہوائی اڈہ",
  flightArrivalAirport: "آمد کا ہوائی اڈہ",
  flightAirportSearchHint: "IATA کوڈ، ہوائی اڈہ، شہر یا ملک سے تلاش کریں",
  flightScheduledDepartureUtc: "طے شدہ روانگی (UTC)",
  flightDuration: "منصوبہ بند دورانیہ",
  flightHours: "گھنٹے",
  flightMinutes: "منٹ",
  flightCruiseAltitude: "کروزنگ بلندی",
  flightAltitudeUnit: "بلندی کی اکائی",
  flightMeters: "میٹر",
  flightFeet: "فٹ",
  flightDepartureTimeZone: "روانگی کا ٹائم زون",
  flightArrivalTimeZone: "آمد کا ٹائم زون",
  flightWaypoints: "اختیاری راستہ نقاط",
  flightWaypointHelp: "ہر سطر میں ایک نقطہ: نام، عرض البلد، طول البلد",
  flightPrepareButton: "آف لائن پرواز تیار کریں",
  flightUseTravelDetails: "سفری تفصیلات میں محفوظ پرواز استعمال کریں",
  flightEdit: "پرواز میں ترمیم کریں",
  flightClear: "پرواز صاف کریں",
  flightEnableGps: "براہِ راست GPS فعال کریں",
  flightDisableGps: "براہِ راست GPS بند کریں",
  flightUseElapsed: "گزرے ہوئے وقت کا اندازہ استعمال کریں",
  flightProgress: "راستے کی پیش رفت",
  flightProgressSlider: "راستے کی پیش رفت کا سلائیڈر",
  flightSource: "ماخذ",
  flightGpsSource: "براہِ راست GPS",
  flightDerivedGpsSource: "اخذ کردہ GPS ٹریک",
  flightRouteSource: "راستے کا اندازہ",
  flightUnavailableSource: "دستیاب نہیں",
  flightLastUpdate: "آخری تازہ کاری",
  flightAccuracy: "درستگی",
  flightLowAccuracy: "GPS کی درستگی کم ہے۔ راستے کا اندازہ زیادہ مستحکم ہو سکتا ہے۔",
  flightGpsDenied: "مقام کی اجازت مسترد کر دی گئی۔ راستے کے اندازے کا موڈ آف لائن دستیاب ہے۔",
  flightGpsUnavailable: "براہِ راست GPS دستیاب نہیں۔ راستے کے اندازے کا موڈ آف لائن دستیاب ہے۔",
  flightGpsStale: "GPS کی تازہ کاری پرانی ہے۔ راستے کا اندازہ دکھایا جا رہا ہے۔",
  flightCoordinates: "مختصات",
  flightAltitude: "بلندی",
  flightRemainingDistance: "باقی فاصلہ",
  flightRemainingTime: "باقی وقت",
  flightRouteDistance: "راستے کا فاصلہ",
  flightQiblaTrue: "قبلہ کی سمت",
  flightTrack: "GPS زمینی ٹریک",
  flightRelativeAngle: "قبلہ کا نسبتی زاویہ",
  flightLeft: "بائیں",
  flightRight: "دائیں",
  flightStraightAhead: "سیدھا آگے",
  flightBehind: "پیچھے",
  flightDiagramLabel: "جہاز کے راستے اور قبلہ کی سمت کا خاکہ",
  flightConfidence: "اعتماد کی سطح",
  flightCurrentPrayer: "موجودہ نماز کا وقت",
  flightNextPrayer: "اگلی نماز",
  flightPreviousPrayer: "پچھلی نماز",
  flightCountdown: "الٹی گنتی",
  flightUtcPrayerTimes: "UTC میں نماز کے اوقات",
  flightZoneTimes: "روانگی اور آمد کے ٹائم زون کے اوقات",
  flightMethod: "حساب کا طریقہ",
  flightNoPlan: "پرواز کے دوران ڈیش بورڈ استعمال کرنے سے پہلے پرواز تیار کریں۔",
  flightPlanSaved: "آف لائن پرواز محفوظ ہو گئی۔",
  flightPlanCleared: "آف لائن پرواز صاف ہو گئی۔",
  flightPlanInvalid: "پرواز کی تفصیلات چیک کریں اور دوبارہ کوشش کریں۔",
  flightDifferentAirports: "روانگی اور آمد کے لیے مختلف ہوائی اڈے منتخب کریں۔",
  flightInvalidDuration: "دورانیہ 15 منٹ سے 24 گھنٹے کے درمیان ہونا چاہیے۔",
  flightInvalidWaypoint: "ایک یا زیادہ راستہ نقاط پڑھے نہیں جا سکے۔",
  flightStorageRecovered: "محفوظ شدہ پرواز کا ڈیٹا پڑھا نہیں جا سکا اور نظر انداز کر دیا گیا۔",
  flightAirportSource: "ہوائی اڈے کا ڈیٹا: عوامی ملکیت والے OurAirports ڈیٹا سے اخذ کردہ شامل آف لائن اشاریہ۔",
};
