export const urduTransportLabelsA: Record<string, string> = {
  carRentalTitle: "کار کرایہ",
  carRentalSubtitle: "نقشے پر موجود کار کرایہ دفاتر تلاش کریں، اور جہاں دستیاب ہو ان کے سرکاری رابطے دیکھیں۔",
  carRentalOpen: "کار کرایہ",
  carRentalBack: "منصوبہ ساز پر واپس جائیں",
  carRentalNotice: "دفاتر کی معلومات صارفین کے فراہم کردہ نقشہ ڈیٹا سے آتی ہیں اور نامکمل یا پرانی ہو سکتی ہیں۔ مقام، اوقات، شرائط، قیمت، بیمہ، ضمانت اور گاڑی کی دستیابی براہِ راست دفتر سے تصدیق کریں۔",
  carRentalAvailabilityNotice: "نتائج میں دفتر دکھائی دینے کا مطلب یہ نہیں کہ گاڑیاں ابھی دستیاب ہیں۔",
  carRentalLiveNotice: "یہ نقشہ تلاش براہِ راست قیمت یا گاڑی کی دستیابی نہیں دکھاتی۔ دستیابی اور آخری قیمت کے لیے دفتر یا اس کی سرکاری ویب سائٹ سے رابطہ کریں۔",
  carRentalUseLocation: "میرا مقام استعمال کریں",
  carRentalManualSearch: "شہر، ہوائی اڈہ یا اسٹیشن تلاش کریں",
  carRentalManualPlaceholder: "شہر، ہوائی اڈہ، ریلوے اسٹیشن...",
  carRentalSearchNear: "قریب تلاش کریں",
  carRentalDestinationSearch: "منزل",
  carRentalAirportSearch: "ہوائی اڈہ",
  carRentalStationSearch: "ریلوے یا بس اسٹیشن",
  carRentalSearch: "تلاش کریں",
  carRentalSearchThisArea: "اس علاقے میں تلاش کریں",
  carRentalRecentre: "میرے مقام پر دوبارہ مرکز کریں",
  carRentalFitResults: "تمام نتائج دکھائیں",
  carRentalRadius: "دائرہ",
  carRentalRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  carRentalSearching: "نقشے پر کار کرایہ دفاتر تلاش ہو رہے ہیں...",
  carRentalLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے منزل تلاش کریں۔",
  carRentalLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  carRentalServiceUnavailable: "نقشہ ڈیٹا سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  carRentalTimedOut: "تلاش کا وقت ختم ہو گیا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  carRentalTooMany: "نتائج بہت زیادہ ہیں۔ چھوٹا دائرہ آزمائیں۔",
  carRentalOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  carRentalCached: "محفوظ کار کرایہ دفاتر دکھائے جا رہے ہیں۔",
  carRentalNoResults: "اس علاقے میں کوئی نقشہ شدہ کار کرایہ دفتر نہیں ملا۔ اس کا مطلب یہ نہیں کہ یہاں کوئی موجود نہیں۔",
  carRentalRetry: "دوبارہ کوشش کریں",
  carRentalIncreaseRadius: "دائرہ بڑھائیں",
  carRentalSearchAnother: "دوسری منزل تلاش کریں",
  carRentalMapView: "نقشہ",
  carRentalListView: "قریبی فہرست",
  carRentalAllOffices: "تمام دفاتر",
  carRentalAirportOffice: "ہوائی اڈے کا کار کرایہ دفتر",
  carRentalCityOffice: "شہری کار کرایہ دفتر",
  carRentalRailwayOffice: "ریلوے اسٹیشن کار کرایہ دفتر",
  carRentalBusOffice: "بس اسٹیشن کار کرایہ دفتر",
  carRentalHotelDesk: "ہوٹل یا عوامی مقام میں کرایہ ڈیسک",
  carRentalIndependentOffice: "آزاد مقامی دفتر",
  carRentalUnknownOffice: "مقام کی قسم نامعلوم",
  carRentalAtAirport: "ہوائی اڈے پر یا قریب",
  carRentalWebsiteAvailable: "سرکاری ویب سائٹ دستیاب",
  carRentalPhoneAvailable: "فون دستیاب",
  carRentalSort: "ترتیب دیں",
  carRentalSortAirport: "ہوائی اڈے کے دفاتر پہلے",
  carRentalSortWebsite: "سرکاری ویب سائٹ دستیاب",
  carRentalLegend: "نقشہ نشانات کی وضاحت",
  carRentalBrand: "برانڈ",
  carRentalOperator: "منتظم",
  carRentalLocationType: "مقام کی قسم",
  carRentalLocationContext: "ہوائی اڈہ یا اسٹیشن",
  carRentalEmail: "ای میل",
  carRentalBookingWebsite: "سرکاری بکنگ ویب سائٹ",
  carRentalBranchRef: "دفتر کا حوالہ",
  carRentalOfficialWebsiteListed: "نقشہ ڈیٹا میں سرکاری ویب سائٹ درج ہے",
  carRentalOfficialBookingListed: "نقشہ ڈیٹا میں سرکاری بکنگ ویب سائٹ درج ہے",
  carRentalOpenOfficialWebsite: "سرکاری ویب سائٹ کھولیں",
  carRentalCallOffice: "دفتر کو کال کریں",
  carRentalChecklistTitle: "بکنگ سے پہلے براہِ راست تصدیق کریں",
  carRentalChecklistIntro: "یہ نقشہ تلاش ہر ملک کے مخصوص قانونی مشورے فراہم نہیں کرتی۔",
  carRentalCheckAge: "ڈرائیور کی کم از کم عمر",
  carRentalCheckLicence: "درست ڈرائیونگ لائسنس کی شرائط",
  carRentalCheckPermit: "بین الاقوامی ڈرائیونگ پرمٹ کی شرائط",
  carRentalCheckDeposit: "ضمانت اور ادائیگی کے طریقے کی شرائط",
  carRentalCheckInsurance: "بیمہ کوریج اور استثنا",
  carRentalCheckFuel: "ایندھن کی پالیسی",
  carRentalCheckMileage: "مائلیج کی حد",
  carRentalCheckDriver: "اضافی ڈرائیور کی فیس",
  carRentalCheckBorder: "سرحد پار کرنے کی پابندیاں",
  carRentalCheckCancel: "منسوخی کی پالیسی",
  carRentalCheckTimes: "گاڑی لینے اور واپس کرنے کے اوقات",
  carRentalCheckLate: "دیر سے واپسی کی فیس",
};
