export const urduTransportLabelsB: Record<string, string> = {
  publicTransportTitle: "عوامی ٹرانسپورٹ",
  publicTransportSubtitle: "قریب ریلوے اسٹیشن، میٹرو اسٹیشن، ٹرام اسٹاپ، بس اسٹیشن اور فیری ٹرمینل تلاش کریں، دستیاب راستوں اور معلومات کے ساتھ۔",
  publicTransportOpen: "عوامی ٹرانسپورٹ",
  publicTransportBack: "منصوبہ ساز پر واپس جائیں",
  publicTransportNotice: "عوامی ٹرانسپورٹ کی معلومات کھلے اور صارفین کے فراہم کردہ نقشہ ڈیٹا سے آتی ہیں اور نامکمل یا پرانی ہو سکتی ہیں۔ لائنیں، اوقات، کرایہ اور رسائی سرکاری آپریٹر سے تصدیق کریں۔",
  publicTransportLiveNotice: "براہِ راست روانگی اور راستہ منصوبہ بندی ابھی دستیاب نہیں۔",
  publicTransportUseLocation: "میرا مقام استعمال کریں",
  publicTransportUseDestination: "سفر کی منزل استعمال کریں",
  publicTransportManualSearch: "دوسرا شہر تلاش کریں",
  publicTransportManualPlaceholder: "شہر یا منزل...",
  publicTransportSearch: "تلاش کریں",
  publicTransportSearchThisArea: "اس علاقے میں تلاش کریں",
  publicTransportRecentre: "نقشہ دوبارہ مرکز کریں",
  publicTransportFitResults: "تمام نتائج دکھائیں",
  publicTransportRadius: "دائرہ",
  publicTransportRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  publicTransportSearching: "نقشے پر عوامی ٹرانسپورٹ تلاش ہو رہی ہے...",
  publicTransportLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے منزل تلاش کریں۔",
  publicTransportLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  publicTransportServiceUnavailable: "نقشہ ڈیٹا سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  publicTransportTimedOut: "تلاش کا وقت ختم ہو گیا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  publicTransportTooMany: "نتائج بہت زیادہ ہیں۔ چھوٹا دائرہ آزمائیں۔",
  publicTransportOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  publicTransportCached: "محفوظ عوامی ٹرانسپورٹ نتائج دکھائے جا رہے ہیں۔",
  publicTransportNoResults: "اس علاقے میں کوئی نقشہ شدہ عوامی ٹرانسپورٹ اسٹاپ یا اسٹیشن نہیں ملا۔ اس کا مطلب یہ نہیں کہ یہاں کوئی موجود نہیں۔",
  publicTransportRetry: "دوبارہ کوشش کریں",
  publicTransportIncreaseRadius: "دائرہ بڑھائیں",
  publicTransportSearchAnother: "دوسرا شہر تلاش کریں",
  publicTransportMapView: "نقشہ",
  publicTransportListView: "قریبی فہرست",
  publicTransportAll: "تمام عوامی ٹرانسپورٹ",
  publicTransportSort: "ترتیب دیں",
  publicTransportLegend: "نقشہ نشانات کی وضاحت",
  transportTrain: "ریلوے اسٹیشن",
  transportMetro: "میٹرو اسٹیشن",
  transportLightRail: "لائٹ ریل اسٹیشن",
  transportTram: "ٹرام اسٹاپ",
  transportBusStation: "بس اسٹیشن",
  transportBusStop: "بس اسٹاپ",
  transportFerry: "فیری ٹرمینل",
  transportOther: "دوسرا عوامی ٹرانسپورٹ اسٹاپ",
  transportType: "ٹرانسپورٹ کی قسم",
  transportOperator: "آپریٹر",
  transportNetwork: "نیٹ ورک",
  transportReference: "حوالہ",
  transportLines: "لائنیں یا راستے",
  transportShelter: "شیڈ",
  transportSeating: "بیٹھنے کی جگہ",
  transportToilets: "بیت الخلا",
  transportToiletsAvailable: "بیت الخلا دستیاب",
  transportShelterAvailable: "شیڈ دستیاب",
  transportOfficialWebsite: "سرکاری ویب سائٹ",
  transportSortType: "ٹرانسپورٹ کی قسم",
};
