export const urduTransportLabelsC: Record<string, string> = {
  taxiTitle: "ٹیکسی خدمات",
  taxiSubtitle: "اپنے مقام یا منزل کے قریب واضح طور پر درج ٹیکسی اسٹینڈ اور ٹیکسی دفاتر تلاش کریں۔",
  taxiOpen: "ٹیکسی خدمات",
  taxiBack: "منصوبہ ساز پر واپس جائیں",
  taxiNotice: "ٹیکسی کی معلومات صارفین کے فراہم کردہ نقشہ ڈیٹا سے آتی ہیں اور نامکمل یا پرانی ہو سکتی ہیں۔ نقشے پر ٹیکسی مقام دکھائی دینے سے لائسنس، حفاظت، قیمت یا موجودہ دستیابی ثابت نہیں ہوتی۔ مقامی طور پر کرایہ، اوقات، ادائیگی اور سرکاری رابطے کی تصدیق کریں۔",
  taxiLiveNotice: "یہ ایپ ابھی ٹیکسی بک نہیں کرتی اور نہ ہی براہِ راست گاڑیاں دکھاتی ہے۔",
  taxiUseLocation: "میرا مقام استعمال کریں",
  taxiUseDestination: "سفر کی منزل استعمال کریں",
  taxiManualSearch: "دوسرا شہر تلاش کریں",
  taxiManualPlaceholder: "شہر یا منزل...",
  taxiSearch: "تلاش کریں",
  taxiSearchThisArea: "اس علاقے میں تلاش کریں",
  taxiRecentre: "نقشہ دوبارہ مرکز کریں",
  taxiFitResults: "تمام نتائج دکھائیں",
  taxiRadius: "دائرہ",
  taxiRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  taxiSearching: "نقشے پر ٹیکسی خدمات تلاش ہو رہی ہیں...",
  taxiLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے منزل تلاش کریں۔",
  taxiLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  taxiServiceUnavailable: "نقشہ ڈیٹا سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  taxiTimedOut: "تلاش کا وقت ختم ہو گیا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  taxiTooMany: "نتائج بہت زیادہ ہیں۔ چھوٹا دائرہ آزمائیں۔",
  taxiOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  taxiCached: "محفوظ ٹیکسی نتائج دکھائے جا رہے ہیں۔",
  taxiNoResults: "اس علاقے میں کوئی واضح ٹیکسی اسٹینڈ یا دفتر نہیں ملا۔ اس کا مطلب یہ نہیں کہ یہاں کوئی موجود نہیں۔",
  taxiRetry: "دوبارہ کوشش کریں",
  taxiIncreaseRadius: "دائرہ بڑھائیں",
  taxiSearchAnother: "دوسرا شہر تلاش کریں",
  taxiMapView: "نقشہ",
  taxiListView: "قریبی فہرست",
  taxiAll: "تمام ٹیکسی خدمات",
  taxiRank: "ٹیکسی اسٹینڈ",
  taxiAirportRank: "ہوائی اڈے کا ٹیکسی اسٹینڈ",
  taxiStationRank: "ریلوے یا میٹرو اسٹیشن ٹیکسی اسٹینڈ",
  taxiBusRank: "بس اسٹیشن ٹیکسی اسٹینڈ",
  taxiOffice: "ٹیکسی دفتر یا ڈسپیچ سروس",
  taxiMotorcycle: "موٹر سائیکل ٹیکسی اسٹینڈ",
  taxiWater: "واٹر ٹیکسی اسٹینڈ",
  taxiOther: "دوسری نقشہ شدہ ٹیکسی سروس",
  taxiPhoneAvailable: "فون دستیاب",
  taxiWheelchairInfo: "وہیل چیئر رسائی کی معلومات دستیاب",
  taxiSort: "ترتیب دیں",
  taxiSortType: "ٹیکسی سروس کی قسم",
  taxiSortContact: "رابطہ معلومات دستیاب",
  taxiLegend: "نقشہ نشانات کی وضاحت",
  taxiType: "ٹیکسی سروس کی قسم",
  taxiCapacity: "گنجائش",
  taxiVehicle: "گاڑی کی قسم",
  taxiLit: "روشنی",
  taxiFee: "کرایے کی معلومات",
  taxiCall: "ٹیکسی سروس کو کال کریں",
};
