export const urduLabels: Record<string, string> = {
  title: "SafarMate",
  subtitle: "مسلمان سفری منصوبہ ساز",
  tagline: "ایمان کے ساتھ منصوبہ بنائیں، سکون سے سفر کریں۔",
  prototype: "",
  language: "زبان",
  city: "شہر",
  cityAutocomplete: "شہر کی خودکار تکمیل",
  cityPlaceholder: "کوئی بھی شہر",
  region: "خطہ",
  allRegions: "تمام خطے",
  startDate: "آغاز کی تاریخ",
  endDate: "اختتام کی تاریخ",
  startHour: "دستیاب وقت سے",
  endHour: "تک",
  groupSize: "گروپ کا سائز",
  budget: "بجٹ",
  interests: "دلچسپیاں",
  walkingAbility: "چلنے کی صلاحیت",
  transportation: "آمدورفت",
  prayerMethod: "نماز کے اوقات کا حساب",
  prayerPreference: "نماز کی ترجیح",
  children: "بچے",
  womenPrayerRequired: "خواتین کے لیے نماز کی جگہ ضروری",
  wuduRequired: "وضو کی سہولت ضروری",
  accessibilityNeeds: "رسائی کی ضروریات",
  halalPreference: "حلال کھانے کی ترجیح",
  plan: "سفری منصوبہ بنائیں",
  replan: "یہاں سے دوبارہ منصوبہ بنائیں",
  sample: "یہ صرف نمونہ ڈیٹا ہے۔ سفر سے پہلے نماز کے اوقات، مسجد کی سہولتیں، کھلنے کے اوقات اور حلال دعووں کی تصدیق کریں۔",
  legend: "معلوماتی نشانات",
  formAria: "منصوبہ ساز کی ترجیحات",
  prayerWindowsAre: "نماز کے اوقات",
  transportEstimatesAre: "اندازاً سفر کا وقت",
  walking: "پیدل",
  publicTransport: "عوامی ٹرانسپورٹ",
  taxi: "ٹیکسی",
  minutesShort: "منٹ",
  evidenceNote: "ثبوت کا نوٹ",
  women: "خواتین",
  wudu: "وضو",
  accessibility: "رسائی",
  facilityInfoMayBeIncomplete: "سہولتوں کی معلومات نامکمل ہو سکتی ہیں",
  facilityAvailable: "دستیاب",
  facilityInfoUnavailable: "معلومات دستیاب نہیں",
  facilityEstimatedInfo: "اندازاً معلومات",
  emptyState: "ابھی کوئی سفری سرگرمی نہیں۔ اپنی ترجیحات منتخب کریں اور منصوبہ بنائیں۔",
  generatePrompt: "منزل اور ترجیحات منتخب کریں، پھر سفری منصوبہ بنائیں دبائیں۔",
  itineraryReady: "سفری منصوبہ تیار ہے۔",
  homeTripsGroup: "آپ کے سفر",
  homeEssentialsGroup: "مسلمانوں کی ضروریات",
  homeTravelToolsGroup: "سفری اوزار",
  savedTripsTitle: "محفوظ سفر",
  savedTripsSubtitle: "اس آلے پر محفوظ سفری منصوبے دوبارہ کھولیں۔",
  savedTripsOpen: "محفوظ سفر",
  savedTripsBack: "منصوبہ ساز پر واپس جائیں",
  saveTrip: "سفر محفوظ کریں",
  saveChanges: "تبدیلیاں محفوظ کریں",
  savedLocally: "اس آلے پر مقامی طور پر محفوظ",
  noCloudSync: "کلاؤڈ ہم آہنگی نہیں",
  unsavedChanges: "غیر محفوظ تبدیلیاں",
  saveFailed: "محفوظ نہیں ہو سکا۔ اسٹوریج بند یا بھرا ہوا ہو سکتا ہے۔",
  savedStatus: "محفوظ",
  renameTrip: "نام تبدیل کریں",
  duplicateTrip: "نقل بنائیں",
  deleteTrip: "حذف کریں",
  reopenTrip: "دوبارہ کھولیں",
  savedTripsEmpty: "ابھی کوئی سفر محفوظ نہیں۔ منصوبہ بنائیں، پھر سفر محفوظ کریں منتخب کریں۔",
  deleteTripConfirm: "محفوظ سفر حذف کریں",
  tripName: "سفر کا نام",
  tripSummary: "سفر کا خلاصہ",
  tripDates: "سفر کی تاریخیں",
  tripDays: "دن",
  tripGroup: "گروپ",
  tripStyle: "انداز",
  editPlan: "منصوبہ ترمیم کریں",
  shareTrip: "سفر شیئر کریں",
  copyItinerary: "سفری منصوبہ کاپی کریں",
  exportCalendar: "کیلنڈر برآمد کریں",
  printItinerary: "پرنٹ / PDF محفوظ کریں",
  itineraryCopied: "سفری منصوبہ کاپی ہو گیا۔",
  calendarDownloaded: "کیلنڈر ڈاؤن لوڈ ہو گیا۔",
  sharingUnavailable: "یہاں شیئرنگ دستیاب نہیں۔ آپ سفری منصوبہ کاپی کر سکتے ہیں۔",
  shareCancelled: "شیئرنگ منسوخ ہو گئی۔",
  unableToShare: "شیئر نہیں کیا جا سکا۔",
  shareLiveInfoWarning: "براہِ راست نقشے، موسم، شرحِ مبادلہ، کھلنے کی حالت اور بیرونی ویب سائٹس کے لیے انٹرنیٹ درکار ہو سکتا ہے؛ دوبارہ تصدیق کریں۔",
  savedSnapshotLabel: "محفوظ سفری منصوبے کی نقل",
  reportProblem: "مسئلہ رپورٹ کریں",
  reportWhatWrong: "کیا غلط ہے؟",
  reportWrongName: "غلط نام",
  reportWrongLocation: "غلط مقام",
  reportClosed: "جگہ بند یا ہٹا دی گئی ہے",
  reportWrongCategory: "غلط زمرہ",
  reportHours: "کھلنے کے اوقات غلط ہیں",
  reportContact: "فون یا ویب سائٹ غلط ہے",
  reportAccessibility: "رسائی کی معلومات غلط ہیں",
  reportHalal: "حلال معلومات غلط ہیں",
  reportOther: "دیگر",
  reportOptionalNote: "اختیاری نوٹ",
  reportOpenSource: "اصل ریکارڈ کھولیں",
  reportOsm: "OpenStreetMap پر رپورٹ یا درست کریں",
  reportOsmAccount: "OpenStreetMap اکاؤنٹ درکار ہو سکتا ہے۔",
  reportAppProblem: "ایپ کا مسئلہ رپورٹ کریں",
  reportGithubAccount: "GitHub اکاؤنٹ درکار ہو سکتا ہے۔",
  reportCopy: "رپورٹ کی تفصیلات کاپی کریں",
  reportShare: "رپورٹ کی تفصیلات شیئر کریں",
  reportCopied: "رپورٹ کاپی ہو گئی۔",
  reportCopyFailed: "کاپی نہیں ہو سکی۔",
  reportExternalNotice: "بیرونی رپورٹ صفحہ کھولنے سے رپورٹ خودکار طور پر جمع نہیں ہوتی۔",
  reportClose: "بند کریں",
  privacyPolicy: "رازداری کی پالیسی",
  supportPage: "مدد",
  developerCredit: "تیار کردہ: Firas Badran",
  supportEmailLabel: "مدد: planetearthkh@gmail.com",
  travelDetails: "سفر کی تفصیلات",
  travelOptional: "اختیاری سفری تفصیلات",
  travelAddDetail: "تفصیل شامل کریں",
  travelChooseType: "تفصیل کی قسم منتخب کریں",
  travelDetailFlight: "پرواز",
  travelDetailAccommodation: "رہائش",
  travelDetailReservation: "بکنگ",
  travelDetailContact: "فراہم کنندہ کا رابطہ",
  travelAirline: "فضائی کمپنی",
  travelFlightNumber: "پرواز نمبر",
  travelDepartureAirport: "روانگی کا ہوائی اڈہ",
  travelArrivalAirport: "آمد کا ہوائی اڈہ",
  travelDepartureDateTime: "روانگی کی تاریخ اور وقت",
  travelArrivalDateTime: "آمد کی تاریخ اور وقت",
  travelDepartureTimeZone: "روانگی کا ٹائم زون",
  travelArrivalTimeZone: "آمد کا ٹائم زون",
  travelPropertyName: "رہائش کا نام",
  travelAddress: "پتہ",
  travelCheckIn: "چیک اِن",
  travelCheckOut: "چیک آؤٹ",
  travelTimeZone: "ٹائم زون",
  travelReservationTitle: "بکنگ کا عنوان",
  travelProvider: "فراہم کنندہ",
  travelStartDateTime: "آغاز کی تاریخ اور وقت",
  travelEndDateTime: "اختتام کی تاریخ اور وقت",
  travelMeetingPoint: "پتہ یا ملاقات کی جگہ",
  travelProviderContactName: "فراہم کنندہ یا رابطے کا نام",
  travelRole: "کردار یا خدمت",
  travelPhone: "فون نمبر",
  travelWebsite: "ویب سائٹ",
  travelBookingReference: "بکنگ حوالہ",
  travelPrivateReference: "نجی — شیئرنگ اور کیلنڈر برآمد سے خارج",
  travelPrivateReferenceExport: "نجی بکنگ حوالے صرف اس آلے پر محفوظ ہوتے ہیں اور شامل نہیں کیے جاتے۔",
  travelNotes: "نوٹس",
  travelSave: "محفوظ کریں",
  travelCancel: "منسوخ کریں",
  travelEdit: "ترمیم کریں",
  travelDelete: "حذف کریں",
  travelDeleteConfirm: "یہ تفصیل حذف کریں؟",
  travelDetailAdded: "تفصیل شامل ہو گئی۔",
  travelDetailUpdated: "تفصیل اپ ڈیٹ ہو گئی۔",
  travelDetailDeleted: "تفصیل حذف ہو گئی۔",
  travelInvalidDate: "غلط تاریخ یا وقت۔",
  travelEndAfterStart: "اختتام آغاز کے بعد ہونا چاہیے۔",
  travelInvalidTimeZone: "غلط ٹائم زون۔",
  travelInvalidWebsite: "غلط ویب سائٹ۔",
  travelRequiredFields: "ضروری خانے مکمل کریں۔",
  travelStoredOnly: "صرف اس آلے پر محفوظ",
  travelStorageNotEncrypted: "براؤزر اسٹوریج خفیہ نہیں ہے",
  travelClearingData: "براؤزر ڈیٹا صاف کرنے سے یہ تفصیلات حذف ہو سکتی ہیں",
  travelSensitiveWarning: "پاسپورٹ، ادائیگی کارڈ، پاس ورڈ یا شناختی دستاویز کی معلومات درج نہ کریں",
  travelNoDetails: "ابھی کوئی سفری تفصیل شامل نہیں۔",
  travelEmptyDescription: "سفری تفصیلات اختیاری ہیں اور محفوظ منصوبے کے ساتھ آف لائن مفید رہتی ہیں۔",
  approximateQibla: "شہر کے مرکز سے اندازاً قبلہ سمت",
  savedAt: "محفوظ",
  storageRecovered: "محفوظ سفر کا اسٹوریج پڑھا نہیں جا سکا۔ موجود درست سفر تبدیل نہیں کیے گئے۔",
  offlineIndicator: "آف لائن — محفوظ سفر دستیاب رہیں گے",
  onlineIndicator: "دوبارہ آن لائن",
  internetRequired: "براہِ راست اوزار کے لیے انٹرنیٹ درکار ہے۔",
  offlineLimitNotice: "محفوظ سفری منصوبے آف لائن دستیاب ہیں۔ براہِ راست نقشے، موسم، کرنسی، راستے اور بیرونی ویب سائٹس کے لیے انٹرنیٹ چاہیے۔",
  invalidEndDate: "اختتام کی تاریخ آغاز سے پہلے نہیں ہو سکتی۔",
  invalidEndTime: "ایک روزہ سفر میں اختتام کا وقت آغاز سے پہلے نہیں ہو سکتا۔",
  invalidGroupSize: "گروپ کا سائز کم از کم 1 ہونا چاہیے۔",
  invalidCity: "منصوبہ بنانے سے پہلے معاون شہر منتخب کریں۔",
  invalidTripTooLong: "سفر زیادہ سے زیادہ 14 دن کے لیے بنایا جا سکتا ہے۔",
  dayHeading: "دن",
  noCities: "اس خطے میں کوئی شہر نہیں ملا۔",
  cityStreetMap: "شہر کا سڑک نقشہ",
  openFullMap: "مکمل نقشہ کھولیں",
  findOnMap: "نقشے پر تلاش کریں",
  mapUnavailable: "نقشہ دستیاب نہیں",
  available: "دستیاب",
  notAvailable: "دستیاب نہیں",
  qibla: "قبلہ",
  qiblaTitle: "قبلہ کی سمت",
  qiblaSubtitle: "کعبہ کی سمت معلوم کرنے کے لیے اپنا مقام استعمال کریں۔",
  qiblaOpen: "قبلہ کھولیں",
  qiblaBack: "منصوبہ ساز پر واپس جائیں",
  qiblaRequestLocation: "میرا مقام استعمال کریں",
  qiblaRequestMotion: "براہِ راست قطب نما شروع کریں",
  qiblaRetry: "دوبارہ کوشش کریں",
  qiblaLoadingLocation: "آپ کا مقام تلاش کیا جا رہا ہے...",
  qiblaLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ مقام کی رسائی فعال کریں یا دوبارہ کوشش کریں۔",
  qiblaLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  qiblaMotionUnavailable: "براہِ راست قطب نما دستیاب نہیں۔ مقررہ قبلہ سمت دکھائی جا رہی ہے۔",
  qiblaMotionDenied: "قطب نما کی اجازت مسترد ہو گئی۔ مقررہ قبلہ سمت دکھائی جا رہی ہے۔",
  qiblaLiveCompass: "براہِ راست قطب نما فعال ہے",
  qiblaFixedBearing: "مقررہ سمت",
  qiblaBearing: "سمت",
  qiblaLocation: "مقام",
  qiblaKaaba: "کعبہ",
  qiblaNorth: "شمال",
  qiblaEast: "مشرق",
  qiblaSouth: "جنوب",
  qiblaWest: "مغرب",
  qiblaDegrees: "درجے",
  prayerSpacesTitle: "مساجد اور نماز کی جگہیں",
  prayerSpacesSubtitle: "اپنے قریب یا منزل کے نزدیک نقشے پر موجود مساجد اور پُرسکون نماز کی جگہیں تلاش کریں۔",
  prayerSpacesOpen: "مساجد اور نماز کی جگہیں",
  prayerSpacesBack: "منصوبہ ساز پر واپس جائیں",
  prayerMapView: "نقشہ",
  prayerListView: "قریبی فہرست",
  prayerUseLocation: "میرا مقام استعمال کریں",
  prayerManualSearch: "شہر یا منزل تلاش کریں",
  prayerManualPlaceholder: "شہر، ہوائی اڈہ، یونیورسٹی، ہسپتال...",
  prayerSearch: "تلاش کریں",
  prayerSearchThisArea: "اس علاقے میں تلاش کریں",
  prayerRadius: "دائرہ",
  prayerRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  prayerSearching: "OpenStreetMap میں تلاش ہو رہی ہے...",
  prayerLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے شہر یا منزل تلاش کریں۔",
  prayerLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  prayerServiceUnavailable: "تلاش کی سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  prayerNoResults: "قریب کوئی جگہ نہیں ملی۔",
  prayerRetry: "دوبارہ کوشش کریں",
  prayerIncreaseRadius: "تلاش کا دائرہ بڑھائیں",
  prayerNotice: "معلومات نامکمل یا پرانی ہو سکتی ہیں۔ سفر سے پہلے رسائی اور اوقات کی تصدیق کریں۔",
  prayerAllPlaces: "تمام جگہیں",
  prayerMosques: "مساجد",
  prayerRooms: "نماز کے کمرے",
  prayerQuietSpaces: "پُرسکون جگہیں",
  prayerOpenNow: "ابھی کھلا ہے",
  prayerWomenArea: "خواتین کی نماز کی جگہ",
  prayerWuduAvailable: "وضو دستیاب ہے",
  prayerWheelchairAccessible: "وہیل چیئر کے لیے قابلِ رسائی",
  prayerSort: "ترتیب دیں",
  prayerNearest: "قریب ترین",
  prayerName: "نام",
  prayerOpenNowSort: "ابھی کھلا ہے",
  prayerTypeMosque: "مسجد",
  prayerTypeRoom: "نماز کا کمرہ",
  prayerTypeQuiet: "پُرسکون نماز کی جگہ",
  prayerDistance: "فاصلہ",
  prayerAddress: "پتہ",
  prayerOpeningHours: "کھلنے کے اوقات",
  prayerWomen: "خواتین کی نماز کی جگہ",
  prayerWudu: "وضو کی سہولت",
  prayerWheelchair: "وہیل چیئر رسائی",
  prayerWebsite: "ویب سائٹ",
  prayerTelephone: "فون",
  prayerVerification: "تصدیق کی حالت",
  prayerVerified: "تصدیق شدہ",
  prayerUnverified: "غیر تصدیق شدہ",
  prayerUnknown: "غیر تصدیق شدہ",
  prayerViewOnMap: "نقشے پر دیکھیں",
  prayerDirections: "راستہ حاصل کریں",
  prayerAppleMaps: "Apple Maps",
  prayerBrowserMap: "براؤزر نقشہ",
  moneyTitle: "رقم اور کرنسی",
  moneySubtitle: "محفوظ حوالہ شرحوں اور مقامی کرنسی کی رہنمائی کے ساتھ بجٹ تبدیل کریں۔",
  moneyOpen: "رقم اور کرنسی",
  moneyBack: "منصوبہ ساز پر واپس جائیں",
  amount: "رقم",
  fromCurrency: "ابتدائی کرنسی",
  toCurrency: "مطلوبہ کرنسی",
  searchCurrency: "کرنسیاں تلاش کریں",
  swapCurrencies: "کرنسیاں تبدیل کریں",
  clear: "صاف کریں",
  refreshRates: "شرحیں تازہ کریں",
  copyResult: "نتیجہ کاپی کریں",
  pairRate: "موجودہ شرح",
  reversePairRate: "الٹی شرح",
  rateDate: "شرح کی تاریخ",
  lastRefreshed: "آخری تازہ کاری",
  destination: "منزل",
  localCurrency: "مقامی کرنسی",
  symbol: "علامت",
  popularCurrencies: "مقبول کرنسیاں",
  loadingCurrencies: "کرنسیاں لوڈ ہو رہی ہیں...",
  loadingRate: "شرحِ مبادلہ لوڈ ہو رہی ہے...",
  rateUpdated: "شرح اپ ڈیٹ ہو گئی۔",
  offline: "آپ آف لائن معلوم ہوتے ہیں۔",
  cachedRate: "محفوظ شرح",
  serviceUnavailable: "شرح کی سروس دستیاب نہیں۔",
  unsupportedCurrency: "یہ کرنسی جوڑا معاون نہیں۔",
  invalidAmount: "درست، غیر منفی رقم درج کریں۔",
  noCachedData: "کوئی محفوظ شرح دستیاب نہیں۔",
  retry: "دوبارہ کوشش کریں",
  sameCurrency: "ایک ہی کرنسی منتخب ہے؛ شرحِ مبادلہ درکار نہیں۔",
  rateNotice: "شرحِ مبادلہ صرف حوالہ ہے اور بینک، کارڈ، ہوٹل یا منی ایکسچینج سے مختلف ہو سکتی ہے۔ ادائیگی سے پہلے آخری شرح اور فیس چیک کریں۔",
  moneyInfo: "مسافر کے لیے مالی معلومات",
  officialCurrency: "سرکاری یا مقامی کرنسی",
  denominations: "عام نوٹ اور سکے",
  cardsAccepted: "عموماً قبول کیے جانے والے کارڈ",
  paymentWarning: "غیر تصدیق شدہ عمومی معلومات پر انحصار نہ کریں؛ سفر سے پہلے مقامی ادائیگی کے طریقے چیک کریں۔",
  rateHistory: "شرح کی تاریخ",
  sevenDays: "7 دن",
  thirtyDays: "30 دن",
  ninetyDays: "90 دن",
  highestRate: "سب سے زیادہ شرح",
  lowestRate: "سب سے کم شرح",
  startRate: "ابتدائی شرح",
  latestRate: "تازہ ترین شرح",
  percentageChange: "فیصد تبدیلی",
  copied: "کاپی ہو گیا۔",
  halalRestaurantsTitle: "حلال ریسٹورنٹس",
  halalRestaurantsSubtitle: "اپنے قریب یا منزل کے نزدیک واضح حلال معلومات والے نقشہ شدہ ریسٹورنٹس تلاش کریں۔",
  halalRestaurantsOpen: "حلال ریسٹورنٹس",
  halalRestaurantsBack: "منصوبہ ساز پر واپس جائیں",
  halalNotice: "معلومات صارفین کے فراہم کردہ نقشہ ڈیٹا سے آتی ہیں اور نامکمل یا پرانی ہو سکتی ہیں۔ حلال حیثیت، سرٹیفکیٹ، اوقات اور مینو کی براہِ راست تصدیق کریں۔",
  halalMeaningNotice: "صرف حلال کا مطلب ہے کہ ڈیٹا کے مطابق تمام کھانا حلال ہے۔ حلال اختیارات کا مطلب ہے کہ صرف کچھ اشیا حلال ہو سکتی ہیں۔",
  halalUseLocation: "میرا مقام استعمال کریں",
  halalManualSearch: "شہر یا منزل تلاش کریں",
  halalManualPlaceholder: "شہر، علاقہ، ہوائی اڈہ...",
  halalSearch: "تلاش کریں",
  halalSearchThisArea: "اس علاقے میں تلاش کریں",
  halalRecentre: "میرے مقام پر دوبارہ مرکز کریں",
  halalFitResults: "تمام نتائج دکھائیں",
  halalRadius: "دائرہ",
  halalRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  halalSearching: "نقشے پر حلال ریسٹورنٹس تلاش ہو رہے ہیں...",
  halalLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ اس کے بجائے شہر یا منزل تلاش کریں۔",
  halalLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  halalServiceUnavailable: "نقشہ ڈیٹا سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  halalTimedOut: "تلاش کا وقت ختم ہو گیا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  halalTooMany: "نتائج بہت زیادہ ہیں۔ چھوٹا دائرہ آزمائیں۔",
  halalNoResults: "اس علاقے میں کوئی نقشہ شدہ حلال ریسٹورنٹ نہیں ملا۔ اس کا مطلب یہ نہیں کہ یہاں کوئی موجود نہیں۔",
  halalNoReliable: "ان فلٹرز سے قابلِ اعتماد حلال معلومات والا کوئی نتیجہ نہیں ملا۔",
  halalCached: "محفوظ ریسٹورنٹ نتائج دکھائے جا رہے ہیں۔",
  halalOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  halalRetry: "دوبارہ کوشش کریں",
  halalIncreaseRadius: "دائرہ بڑھائیں",
  halalSearchAnotherCity: "دوسرا شہر تلاش کریں",
  halalMapView: "نقشہ",
  halalListView: "قریبی فہرست",
  halalAllReliable: "تمام قابلِ اعتماد نتائج",
  halalOnly: "صرف حلال",
  halalOptions: "حلال اختیارات",
  halalCertificationListed: "سرٹیفکیٹ درج ہے",
  halalLegacy: "پرانی حلال علامت",
  halalPossible: "ممکن / غیر تصدیق شدہ",
  halalRestaurant: "ریسٹورنٹ",
  halalFastFood: "فاسٹ فوڈ",
  halalCafe: "کیفے",
  halalFoodCourt: "فوڈ کورٹ",
  halalOpenNow: "ابھی کھلا ہے",
  halalTakeaway: "ٹیک اوے",
  halalDelivery: "ڈیلیوری",
  halalWheelchair: "وہیل چیئر کے لیے قابلِ رسائی",
  halalCuisine: "کھانے کی قسم",
  halalAllCuisines: "تمام کھانے",
  halalSort: "ترتیب دیں",
  halalNearest: "قریب ترین",
  halalSortName: "نام",
  halalSortStatus: "حلال حیثیت",
  halalSortOpen: "ابھی کھلا ہے",
  halalSortCuisine: "کھانے کی قسم",
  halalCertificationNotice: "اصل ڈیٹا میں سرٹیفکیٹ درج ہے",
  halalLegacyNotice: "پرانی غیر تصدیق شدہ حلال علامت",
  halalPossibleNotice: "اصل ڈیٹا میں ممکنہ حلال ذکر ہے؛ براہِ راست تصدیق کریں۔",
  halalOpeningUnavailable: "کھلنے کی حالت دستیاب نہیں",
  halalOpen: "ابھی کھلا ہے",
  halalClosed: "ابھی بند ہے",
  halalCuisineLabel: "کھانے کی قسم",
  halalMenu: "مینو",
  halalPrice: "قیمت کی سطح",
  halalOutdoor: "باہر بیٹھنے کی جگہ",
  halalInfoIssue: "معلومات غلط یا نامکمل ہیں؟",
  halalCopyDetails: "تفصیلات کاپی کریں",
  halalCopiedDetails: "تفصیلات کاپی ہو گئیں۔",
  halalLegend: "نقشہ نشانات کی وضاحت",
  weatherTitle: "موسم",
  weatherSubtitle: "اپنی منزل کے موجودہ حالات، گھنٹہ وار پیش گوئی اور سفری موسمی اشاریے دیکھیں۔",
  weatherOpen: "موسم",
  weatherBack: "منصوبہ ساز پر واپس جائیں",
  weatherNotice: "پیش گوئیاں بدل سکتی ہیں اور مقامی حالات سے مختلف ہو سکتی ہیں۔ شدید موسم اور اہم سفری فیصلوں کے لیے سرکاری موسمی سروس چیک کریں۔",
  weatherTravelNotice: "یہ پیش گوئی پر مبنی سفری اشاریے ہیں، سرکاری ہنگامی انتباہات نہیں۔ مقامی حکام اور سرکاری موسمی سروس کی ہدایات پر عمل کریں۔",
  weatherAttribution: "موسمی ڈیٹا Open-Meteo سے",
  weatherUseLocation: "میرا مقام استعمال کریں",
  weatherUseDestination: "سفر کی منزل استعمال کریں",
  weatherManualSearch: "دوسرا شہر تلاش کریں",
  weatherManualPlaceholder: "شہر یا منزل...",
  weatherRecentDestinations: "حالیہ منزلیں",
  weatherSearch: "تلاش کریں",
  weatherRefresh: "تازہ کریں",
  weatherRetry: "دوبارہ کوشش کریں",
  weatherSearchAnother: "دوسرا شہر تلاش کریں",
  weatherRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  weatherLocationDenied: "مقام کی اجازت مسترد ہو گئی۔ دستی تلاش استعمال کریں۔",
  weatherLocationUnavailable: "مقام اس آلے یا براؤزر پر دستیاب نہیں۔",
  weatherLoading: "موسم لوڈ ہو رہا ہے...",
  weatherUpdated: "ابھی تازہ کیا گیا۔",
  weatherCached: "محفوظ موسم",
  weatherOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ موسم دکھایا جا رہا ہے۔",
  weatherUnavailable: "موسم کی سروس دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  weatherTimedOut: "موسم کی درخواست کا وقت ختم ہو گیا۔",
  weatherInvalid: "غلط موسمی جواب۔",
  weatherNoCached: "اس مقام کے لیے محفوظ موسم دستیاب نہیں۔",
  weatherUnsupported: "یہ مقام معاون نہیں۔",
  weatherCurrent: "موجودہ موسم",
  weatherHourly: "گھنٹہ وار پیش گوئی",
  weatherNoLaterHourly: "بعد کے گھنٹوں کی پیش گوئی دستیاب نہیں۔",
  weatherDaily: "7 روزہ پیش گوئی",
  weatherTravel: "سفری حالات",
  weatherPacking: "موسم کی بنیاد پر عمومی تجاویز",
  weatherPrayer: "نماز کے اوقات کے آس پاس موسم",
  weatherUnits: "اکائیاں",
  weatherTempUnit: "درجہ حرارت",
  weatherWindUnit: "ہوا",
  weatherPrecipUnit: "بارش",
  weatherCelsius: "سیلسیئس",
  weatherFahrenheit: "فارن ہائیٹ",
  weatherKmh: "کلومیٹر/گھنٹہ",
  weatherMph: "میل/گھنٹہ",
  weatherMs: "میٹر/سیکنڈ",
  weatherKnots: "ناٹ",
  weatherMm: "ملی میٹر",
  weatherInch: "انچ",
  weatherCondition: "حالت",
  weatherFeelsLike: "محسوس ہونے والا",
  weatherHighLow: "زیادہ / کم",
  weatherHumidity: "نمی",
  weatherWind: "ہوا",
  weatherGusts: "تیز جھونکے",
  weatherCloud: "بادل",
  weatherUv: "UV اشاریہ",
  weatherVisibility: "حدِ نگاہ",
  weatherValueUnavailable: "دستیاب نہیں",
  weatherSunrise: "طلوعِ آفتاب",
  weatherSunset: "غروبِ آفتاب",
  weatherDayNight: "دن / رات",
  weatherLastUpdated: "آخری تازہ کاری",
  weatherRainSnow: "بارش یا برف",
  weatherExpand48: "48 گھنٹے دکھائیں",
  weatherShow24: "24 گھنٹے دکھائیں",
  weatherLocalTime: "مقامی وقت",
  weatherTimezone: "ٹائم زون",
  weatherCoordinates: "مختصات",
  weatherDaylight: "دن",
  weatherNight: "رات",
  weatherClear: "صاف آسمان",
  weatherMainlyClear: "زیادہ تر صاف",
  weatherPartlyCloudy: "جزوی ابر آلود",
  weatherOvercast: "مکمل ابر آلود",
  weatherFog: "دھند",
  weatherDrizzle: "بوندا باندی",
  weatherRain: "بارش",
  weatherFreezingRain: "منجمد بارش",
  weatherSnow: "برف",
  weatherSnowShowers: "برفانی بوچھاڑ",
  weatherRainShowers: "بارش کی بوچھاڑ",
  weatherThunderstorm: "گرج چمک",
  weatherThunderstormHail: "اولوں کے ساتھ گرج چمک",
  weatherUnknown: "نامعلوم حالات",
  weatherIndicatorRain: "بارش کا امکان",
  weatherIndicatorSnow: "برف کا امکان",
  weatherIndicatorWind: "تیز ہوا",
  weatherIndicatorUv: "زیادہ UV",
  weatherIndicatorVisibility: "کم حدِ نگاہ",
  weatherIndicatorHot: "بہت گرم حالات",
  weatherIndicatorCold: "سرد حالات",
  weatherIndicatorThunderstorm: "گرج چمک کا امکان",
  weatherPackUmbrella: "چھتری ساتھ رکھیں",
  weatherPackJacket: "ہلکی جیکٹ ساتھ رکھیں",
  weatherPackCold: "سرد موسم کی تیاری کریں",
  weatherPackSun: "دھوپ سے بچاؤ استعمال کریں",
  weatherPackFootwear: "بارش یا برف کے لیے مناسب جوتے پہنیں",
  weatherPackWater: "گرم موسم میں پانی ساتھ رکھیں",
  attractionsTitle: "سیاحتی مقامات",
  attractionsOpen: "سیاحتی مقامات",
  attractionsBack: "منصوبہ ساز پر واپس جائیں",
  attractionsUseLocation: "میرا مقام استعمال کریں",
  attractionsUseDestination: "سفر کی منزل استعمال کریں",
  attractionsManualSearch: "دوسرا شہر تلاش کریں",
  attractionsSearch: "تلاش کریں",
  attractionsSearchAnother: "دوسری منزل تلاش کریں",
  attractionsRequestingLocation: "مقام کی درخواست ہو رہی ہے...",
  attractionsSearching: "نقشے پر سیاحتی مقامات تلاش ہو رہے ہیں...",
  attractionsTimedOut: "تلاش میں زیادہ وقت لگا۔ چھوٹا دائرہ آزمائیں یا دوبارہ کوشش کریں۔",
  attractionsOffline: "آپ آف لائن معلوم ہوتے ہیں۔ دستیاب ہونے پر محفوظ نتائج دکھائے جا رہے ہیں۔",
  attractionsCached: "محفوظ سیاحتی مقامات دکھائے جا رہے ہیں۔",
  attractionsNoResults: "اس علاقے میں کوئی نقشہ شدہ سیاحتی مقام نہیں ملا۔",
  attractionsMapView: "نقشہ",
  attractionsListView: "قریبی فہرست",
  attractionsAll: "تمام سیاحتی مقامات",
  attractionsHistoric: "تاریخی مقامات",
  attractionsMuseum: "عجائب گھر",
  attractionsGallery: "آرٹ گیلریاں",
  attractionsMonument: "یادگاریں",
  attractionsReligious: "مذہبی ورثہ",
  attractionsViewpoint: "نظارہ گاہیں",
  attractionsNatural: "قدرتی مقامات",
  attractionsPark: "پارک اور باغات",
  attractionsCategory: "زمرہ",
  attractionsAdmission: "داخلہ",
  attractionsDetails: "تفصیلات",
  attractionsClose: "تفصیلات بند کریں",
  attractionsReadMore: "ویکیپیڈیا پر مزید پڑھیں",
};
